import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

describe('case-studies page script wiring', () => {
  it('uses the shared navigation script without a redundant page-specific theme script', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('../shared/nav.js');
    expect(html).not.toContain('cases.js');
  });

  it('documents public-site evidence and the case promotion workflow', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('정부24·홈택스·복지로·국민건강보험·국민신문고·고용24·전자가족관계등록시스템·서울특별시 응답소 대표 사이트 순회와 대한민국법원 보조 표본에서 수집한 KRDS UX Writing Before/After 사례와 KRDS 연결, 사례 승격 기준.');
    expect(html).toContain('대표 사이트 순회에서 반복되는 자격·상태·오류·결과 패턴을 Before/After로 재구성했습니다.');
    expect(html).toContain('각 카드에서 관찰 사이트, KRDS 컴포넌트, 사례 승격 단서를 함께 확인하세요.');
    expect(html).toContain('대표 사이트 8종은 정부24·홈택스·복지로·국민건강보험·국민신문고·고용24·전자가족관계등록시스템·서울특별시 응답소이고, 권리구제·완료 뒤 후속 흐름은 대한민국법원 보조 표본으로 함께 봅니다.');
    expect(html).toContain('실제 사례를 추가하는 방법');
    expect(html).toContain('아카이브에서 사례 카드로 넘어가는 가장 짧은 운영 경로');
    expect(html).toContain('대표 사이트 순회에서는 정부24·홈택스·전자가족관계등록시스템 3개 기관 deep archive를 기준점으로 삼고');
    expect(html).toContain('원문 3개+CTA 1개');
    expect(html).toContain('아카이브에 비슷한 카드가 있어도 새 화면 원문 없이 바로 승격하지 않습니다.');
    expect(html).toContain('새 CASE 번호부터 만들지 말고 기존 CASE 묶음에 먼저 붙입니다.');
    expect(html).toContain('승격 단위는 언제나 <code>용어 1개</code>가 아니라 <code>화면 단계 묶음</code>입니다.');
    expect(html).toContain('한 번의 순회마다 최소 산출물을 남깁니다.');
    expect(html).toContain('새 사전 후보 3개, 사례 카드 후보 2개, KRDS 컴포넌트 보강 포인트 1개, 공통 원칙 승격 여부 1개');
    expect(html).toContain('원칙 축별 이번 라운드 시작표');
    expect(html).toContain('무번역 축: 동의·본인확인, 복지·고용 계산, 세무·법원 메뉴를 먼저 봅니다.');
    expect(html).toContain('정보핵심화 축: 상태·결과, 완료, 완료 뒤 후속 흐름 화면을 먼저 봅니다.');
    expect(html).toContain('심리적안전망 축: 세션 종료, 기한 임박, 비가역 결정, 지연 상태를 먼저 봅니다.');
    expect(html).toContain('표기법·맞춤법 축: 표 헤더, 상태 배지, 메뉴명, 검색 레이블을 먼저 봅니다.');
    expect(html).toContain('컴포넌트 축: Button, Search, Modal, Table, Structured list, Result page 여섯 묶음을 먼저 채웁니다.');
    expect(html).toContain('거버넌스 축: 라운드 종료 직후 코퍼스, 사례 카드, 원칙, 테스트가 함께 움직였는지 먼저 확인합니다.');
    expect(html).toContain('이번 라운드 우선순위는 새 원칙 번호를 더 만드는 것보다 어떤 원칙 축에 어떤 대표 사이트 근거와 KRDS 조합을 더 붙일지 선명하게 만드는 데 둡니다.');
    expect(html).toContain('새 실화면을 받은 직후 10분 판정 루틴');
    expect(html).toContain('1분: 화면 유형 1개만 고릅니다.');
    expect(html).toContain('10분: 같은 라운드 동기화 자산을 적습니다.');
    expect(html).toContain('화면 유형 + 실패 패턴 + 바꿀 문장 + KRDS 조합 + 다음 자산');
    expect(html).toContain('KRDS/Figma로 넘길 최소 산출물');
    expect(html).toContain('Description: 실패 패턴 1문장 + 바꿀 공식 + 연결 CASE/원칙 URL을 적습니다.');
    expect(html).toContain('has_deadline');
    expect(html).toContain('has_next_action');
    expect(html).toContain('사례 카드만 만들고 Figma 기본값·설명·숨은 레이블 메모를 비워 두면 KRDS 연계가 끝난 것으로 보지 않습니다.');
    expect(html).toContain('이번 라운드 KRDS/Figma 반영 예시');
    expect(html).toContain('국민건강보험 <code>질병명·병원 이름 검색</code>, <code>피부양자·산정특례 안내</code>, <code>보험료 산정</code>');
    expect(html).toContain('질병명 또는 병원 이름을 입력해 다시 찾아보세요');
    expect(html).toContain('고용24 <code>실업인정 인터넷 신청</code>, <code>조기재취업수당 안내</code>');
    expect(html).toContain('실업급여를 확인하는 날까지 재취업 활동을 등록해 주세요');
    expect(html).toContain('조기재취업수당 대상과 확인 서류 보기');
    expect(html).toContain('서울특별시 응답소 <code>질의응답·답변원문</code>, <code>민원 신청하기 / 결과보기</code>');
    expect(html).toContain('현재 민원 결과 보기');
    expect(html).toContain('화면 유형별 최소 질문');
    expect(html).toContain('자격·조건 화면: 대상 여부 / 기준값 / 탈락 조건 / 자가 확인 경로');
    expect(html).toContain('완료 뒤 후속 흐름 화면: 후속 행동 / 자동 반영과 별도 신청·신고 / 이의·재심사 기한 / 권리구제 경로');
    expect(html).toContain('UX/UI 검수 보조 질문');
    expect(html).toContain('정보 위계: 제목·상태·기한·다음 행동 가운데 지금 가장 먼저 봐야 할 1문장이 첫 블록에 올라와 있는지 확인합니다.');
    expect(html).toContain('접근성·숨은 텍스트: 버튼·링크·배너가 스크린리더에도 목적과 상태를 함께 읽어 주는지, 새 창·순번·토글 여부만 남지 않았는지 확인합니다.');
    expect(html).toContain('사전 승격보다 KRDS 조합 개선으로 먼저 다룹니다.');
    expect(html).toContain('UX/UI 검수 축별 바로 다시 볼 CASE 묶음');
    expect(html).toContain('정보 위계 축: CASE 52 <code>중대한 결정 안내</code>, CASE 55 <code>심사·판정 절차 안내</code>, CASE 5·42·54·55·56 <code>상태·결과 묶음</code>, CASE 31·32·33 <code>결과 뒤 후속 흐름 묶음</code>을 먼저 다시 봅니다.');
    expect(html).toContain('선택·분기 축: CASE 34 <code>비교 선택 안내</code>, CASE 18·58 <code>온라인/방문 분기 + 담당 기관·관할 안내</code>, CASE 19 <code>신청인 유형 분기</code>, CASE 22 <code>증명서 종류 선택</code>, CASE 23 <code>공개 범위 선택</code>, CASE 60 <code>절차 선택 안내</code>를 먼저 다시 봅니다.');
    expect(html).toContain('입력·첨부 축: CASE 20 <code>조건부 필수 항목</code>, CASE 24 <code>첨부 파일 업로드</code>, CASE 38·11·59 <code>폼 도움말 + 동의 화면 + 대리·위임 권한</code>를 먼저 다시 봅니다.');
    expect(html).toContain('상태·안심 축: CASE 16 <code>세션 종료 흐름</code>, CASE 45 <code>기간 제한 서비스 안내</code>, CASE 46 <code>유지 조건 안내</code>, CASE 47 <code>긴급 연결 안내</code>, CASE 56 <code>대기·지연 상태 안내</code>를 먼저 다시 봅니다.');
    expect(html).toContain('접근성·숨은 텍스트 축: CASE 51 <code>접근성 레이블 정리</code>, CASE 49 <code>탐색 레이블 정리</code>, CASE 10 <code>검색창</code>, CASE 39 <code>홈택스 메뉴 이름</code>을 먼저 다시 봅니다.');
    expect(html).toContain('축별 검수에서 2개 이상 CASE가 같은 이유로 걸리면 사례 카드만 고치지 말고 <code>사전</code>, <code>7장 컴포넌트 규칙</code>, <code>부록 D</code>까지 같은 라운드에서 함께 갱신합니다.');
    expect(html).toContain('표기 QA를 사례 카드·krds-lint·KRDS/Figma handoff로 묶는 메모');
    expect(html).toContain('표 헤더: CASE 4 <code>신청자격 / 구비서류 / 처리기간</code>는 CASE 4 handoff + <code>krds-lint</code> fixture + Table + Structured list를 같이 남깁니다.');
    expect(html).toContain('상태표 레이블: CASE 5 <code>처리기관 / 답변예정일 / 등록일</code>는 CASE 5 handoff + <code>krds-lint</code> fixture + Status badge + Timeline을 같이 남깁니다.');
    expect(html).toContain('탐색 레이블: CASE 49 + CASE 39 <code>전자증명서안내 / 부가가치세예정신고 / 증명서발급</code>는 Description, 기본 예시 문구, 숨은 레이블 메모를 같이 남깁니다.');
    expect(html).toContain('숨은 레이블: CASE 51 <code>서비스 상세 이동 / 1번째 배너 / AI 켜기 / ... 새창</code>는 보이는 이름, 현재 상태, 새 탭·새 창 여부를 같이 고정합니다.');
    expect(html).toContain('기호 압축: CASE 39·40·49 <code>전자고지(송달) 신청 및 해지 / 국선대리인 신청(불복청구서 제출전)/(제출후)</code>는 린터 fixture와 Figma Description을 같은 라운드에서 같이 갱신합니다.');
    expect(html).toContain('표기 QA는 <code>krds-lint</code>만 고치거나 사례 카드만 고치고 끝내지 않습니다.');
    expect(html).toContain('수집 직후 분류 표');
    expect(html).toContain('금지 표현 1개 + 대체어가 또렷하면 → 2.1 사전 후보');
    expect(html).toContain('처리 중');
    expect(html).toContain('순회 로그 한 행 예시');
    expect(html).toContain('정부24 <code>전입신고 완료</code>: 화면 유형은 <code>완료 뒤 후속 흐름</code>');
    expect(html).toContain('홈택스 <code>국세 환급금 조회</code>: 화면 유형은 <code>상태·결과</code>');
    expect(html).toContain('전자가족관계등록시스템 <code>전자 발급본 안내</code>: 화면 유형은 <code>조회·발급·공개 범위</code>');
    expect(html).toContain('대한민국법원 <code>지급명령 이의신청</code>: 화면 유형은 <code>완료 뒤 후속 흐름</code>');
    expect(html).toContain('한 행을 다 채우지 못하면 새 CASE 번호부터 만들지 않습니다.');
    expect(html).toContain('사전 승격 보류 기준');
    expect(html).toContain('외국인등록번호 / 영세율 신고');
    expect(html).toContain('이메일 / 민사 등 사건진행 알림서비스');
    expect(html).toContain('처리 중 / 승인');
    expect(html).toContain('홍길동');
    expect(html).toContain('2026.01~2026.12');
    expect(html).toContain('일반화 전에는 사전에 올리지 않습니다.');
    expect(html).toContain('긍정 사례·원칙 유지');
    expect(html).toContain('민원 신청하기');
    expect(html).toContain('검색어');
    expect(html).toContain('구조화 목록');
    expect(html).toContain('비회원 이용');
    expect(html).toContain('발급 보관 90일');
    expect(html).toContain('기간 제한');
    expect(html).toContain('유지 조건');
    expect(html).toContain('기한 임박');
    expect(html).toContain('예상·확정 차이');
    expect(html).toContain('이용권·포인트');
    expect(html).toContain('사전 비대상으로 유지합니다.');
    expect(html).toContain('긍정 사례 카드');
    expect(html).toContain('KRDS 컴포넌트 보강');
    expect(html).toContain('실화면 재방문 표본');
    expect(html).toContain('구조 규칙 우선 유지');
    expect(html).toContain('전입신고 / 사업자 등록 사항 정정 신청 / 집행문 부여 신청');
    expect(html).toContain('전입신고 / 사업자 등록 사항 정정 신청 / 가족관계등록부 정정');
    expect(html).toContain('CASE 18 + CASE 58');
    expect(html).toContain('이메일 / 전자고지(송달) 신청 및 해지 / 민사 등 사건진행 알림서비스');
    expect(html).toContain('일반화 후 재판정');
    expect(html).toContain('Checkbox/Radio + Helper text');
    expect(html).toContain('Notice banner + Structured list');
    expect(html).toContain('Result page + Link');
    expect(html).toContain('이번 라운드에서 바로 쓰는 빠른 판정 예시');
    expect(html).toContain('2장 무번역 우선순위를 CASE로 바로 연결하는 시작표');
    expect(html).toContain('동의·본인확인 묶음: CASE 38');
    expect(html).toContain('CASE 38 <code>폼 도움말</code> + CASE 11 <code>동의 화면</code> + CASE 59 <code>대리·위임 권한</code>');
    expect(html).toContain('정부24·홈택스·국민신문고처럼 동의 단계가 많은 서비스에서');
    expect(html).toContain('복지·고용 계산 묶음: CASE 6');
    expect(html).toContain('CASE 6 <code>고용24 제도 안내</code> + CASE 7 <code>복지로 자격 계산</code> + CASE 8 <code>고용24 실업인정</code>');
    expect(html).toContain('복지로·고용24 화면에서 법령 용어가 계산 순서, 행동 날짜, 준비 서류보다 먼저 나오지 않는지 확인합니다.');
    expect(html).toContain('실업인정 대상기간, 조기재취업수당, 소정급여일수, 통신판매중개자, 노무제공플랫폼사업자');
    expect(html).toContain('노무제공플랫폼사업자는 배달·대리운전처럼 일을 연결하는 플랫폼 사업자를 말합니다.');
    expect(html).toContain('조기재취업수당 안내는 첫 블록에서 누가 대상인지, 언제 다시 취업했는지, 무엇으로 확인하는지를 먼저 보여줘야 합니다.');
    expect(html).toContain('실업 신고 뒤 14일이 지난 후 다시 취업했고, 남은 지급일이 절반 이상인지 먼저 확인하면 수당 신청 대상을 빠르게 판단할 수 있습니다.');
    expect(html).toContain('재취업한 날 또는 사업을 시작한 날부터 12개월이 지난 뒤 청구하므로');
    expect(html).toContain('12개월이 지난 뒤 청구 준비하기');
    expect(html).toContain('실업급여를 확인하는 날');
    expect(html).toContain('활동을 확인하는 서류');
    expect(html).toContain('고용24 실업급여 인정 절차 안내, 실업인정 인터넷 신청.');
    expect(html).toContain('실업인정일까지 등록하지 못하면 이번 회차 지급 확인이 늦어지거나 다시 확인이 필요할 수 있습니다.');
    expect(html).toContain('실업인정일이 지났다면 고용센터 또는 신청 내역에서 다음 회차와 보완 경로를 확인해 주세요.');
    expect(html).toContain('빨리 다시 취업하면 받는 수당');
    expect(html).toContain('남은 지급일');
    expect(html).toContain('소득인정액 / 소득평가액 / 소득환산액 / 기준 중위소득');
    expect(html).toContain('가구 소득·재산 합산액을 확인합니다.');
    expect(html).toContain('가구 소득·재산 합산액');
    expect(html).toContain('복지로 의료급여·교육급여 모의계산, 복지서비스 모의계산·신청 안내.');
    expect(html).toContain('세무·법원 메뉴 묶음: CASE 39');
    expect(html).toContain('CASE 39 <code>홈택스 메뉴 이름</code> + CASE 40 <code>복수 과업 메뉴</code> + CASE 49 <code>탐색 레이블 정리</code>');
    expect(html).toContain('홈택스·대한민국법원처럼 메뉴가 곧 과업인 화면에서 메뉴 이름만 읽고도 과업 동사, 단계 분기, 클릭 전 의미가 드러나는지 확인합니다.');
    expect(html).toContain('사전 승격');
    expect(html).toContain('CASE 확장');
    expect(html).toContain('7장 컴포넌트 규칙');
    expect(html).toContain('다음 순회에서 먼저 다시 볼 CASE 묶음');
    expect(html).toContain('Button 묶음: CASE 39');
    expect(html).toContain('결과 연결 묶음: CASE 37 <code>결과 연결 CTA</code>를 먼저 봅니다.');
    expect(html).toContain('Button 묶음 바로 판정표');
    expect(html).toContain('메뉴 진입: 메뉴 이름만 읽고도 지금 할 행동, 얻는 결과, 대상 조건이 보이는지 확인합니다.');
    expect(html).toContain('민원 신청하기 / 참여 이력조회 / 민원 결과보기');
    expect(html).toContain('추납 신청 / 신고 선택 / 강제집행 신청');
    expect(html).toContain('원문 3개 + 강조 버튼 1개 + 결과 뒤 CTA 1개 + KRDS 조합 1개');
    expect(html).toContain('Search 묶음: CASE 10');
    expect(html).toContain('Search 묶음 바로 판정표');
    expect(html).toContain('입력 전: 검색 전에 무엇을 넣어야 하는지와');
    expect(html).toContain('전자증명서 안내 / 부가가치세 예정 신고');
    expect(html).toContain("'청년 주택' 검색 결과가 없습니다. 지역명이나 제도 이름으로 다시 검색해 보세요");
    expect(html).toContain('원문 3개 + 입력 범위 1개 + 결과 카드 또는 추천 레이블 1개 + 재검색 단서 1개 + KRDS 조합 1개');
    expect(html).toContain('Modal 묶음 바로 판정표');
    expect(html).toContain('만료 전 경고: <code>로그인·실명확인 정보 120분 유지</code>, <code>5분 뒤 자동으로 로그아웃됩니다</code>처럼 남은 시간과 자동 종료 시점이 먼저 보이는지 확인합니다.');
    expect(html).toContain('로그인 유지하기 / 다시 로그인하기 / 메인으로 가기');
    expect(html).toContain('원문 3개 + 남은 시간 1개 + 임시 저장 문장 1개 + 재진입 CTA 1개 + KRDS 조합 1개');
    expect(html).toContain('검색 결과 카드·추천 레이블의 클릭 전 의미');
    expect(html).toContain('Modal 묶음: CASE 16');
    expect(html).toContain('비교 선택 묶음: CASE 34 <code>비교 선택 안내</code>를 먼저 봅니다.');
    expect(html).toContain('첫 분기 영역 묶음: CASE 18 <code>온라인/방문 분기</code> + CASE 58 <code>담당 기관·관할 안내</code>를 같이 봅니다.');
    expect(html).toContain('신청인 유형 묶음: CASE 19 <code>신청인 유형 분기</code>를 먼저 봅니다.');
    expect(html).toContain('조건부 필수 묶음: CASE 20 <code>조건부 필수 항목</code>을 먼저 봅니다.');
    expect(html).toContain('알림 채널 묶음: CASE 21 <code>알림 채널별 수신 내용</code>을 먼저 봅니다.');
    expect(html).toContain('증명서 종류 묶음: CASE 22 <code>증명서 종류 선택</code>을 먼저 봅니다.');
    expect(html).toContain('공개 범위 묶음: CASE 23 <code>공개 범위 선택</code>을 먼저 봅니다.');
    expect(html).toContain('첨부 파일 묶음: CASE 24 <code>첨부 파일 업로드</code>를 먼저 봅니다.');
    expect(html).toContain('절차 선택 묶음: CASE 60 <code>절차 선택 안내</code>를 먼저 봅니다.');
    expect(html).toContain('대리·위임 권한 묶음: CASE 59 <code>대리·위임 권한</code>을 먼저 봅니다.');
    expect(html).toContain('예상 계산 묶음: CASE 35 <code>예상 계산 안내</code>를 먼저 봅니다.');
    expect(html).toContain('예상값 묶음: CASE 36 <code>예상값 안내</code>를 먼저 봅니다.');
    expect(html).toContain('예상·정산 묶음: CASE 41 <code>예상과 확정 차이</code> + CASE 42 <code>확정 결과 설명</code>를 같이 봅니다.');
    expect(html).toContain('기간 제한 묶음: CASE 45 <code>기간 제한 서비스 안내</code>를 먼저 봅니다.');
    expect(html).toContain('유지 조건 묶음: CASE 46 <code>유지 조건 안내</code>를 먼저 봅니다.');
    expect(html).toContain('긴급 연결 묶음: CASE 47 <code>긴급 연결 안내</code>를 먼저 봅니다.');
    expect(html).toContain('병행 절차 묶음: CASE 48 <code>병행 절차 안내</code>를 먼저 봅니다.');
    expect(html).toContain('상담·연락처 묶음: CASE 50 <code>상담·연락처 안내</code>를 먼저 봅니다.');
    expect(html).toContain('중대한 결정 묶음: CASE 52 <code>중대한 결정 안내</code>를 먼저 봅니다.');
    expect(html).toContain('이용 불가 묶음: CASE 25 <code>이용 불가 안내</code>를 먼저 봅니다.');
    expect(html).toContain('조회·열람 묶음: CASE 53 <code>조회·열람 범위 안내</code>를 먼저 봅니다.');
    expect(html).toContain('변경·승인 결과 묶음: CASE 54 <code>변경·승인 결과 안내</code>를 먼저 봅니다.');
    expect(html).toContain('심사·판정 절차 묶음: CASE 55 <code>심사·판정 절차 안내</code>를 먼저 봅니다.');
    expect(html).toContain('대기·지연 상태 묶음: CASE 56 <code>대기·지연 상태 안내</code>를 먼저 봅니다.');
    expect(html).toContain('복수 조건 묶음: CASE 57 <code>복수 조건 체크리스트 안내</code>를 먼저 봅니다.');
    expect(html).toContain('Table·Structured list 묶음: CASE 4');
    expect(html).toContain('상태·결과 묶음: CASE 5');
    expect(html).toContain('결과 뒤 후속 흐름 묶음: CASE 31');
    expect(html).toContain('Table·Structured list 묶음 바로 판정표');
    expect(html).toContain('CASE 4 <code>정부24 신청 상세</code> + CASE 5 <code>민원 처리 상태</code> + CASE 13 <code>재발급 화면</code> + CASE 27 <code>전자 발급본 안내</code>');
    expect(html).toContain('CASE 5 <code>민원 처리 상태</code> + CASE 42 <code>확정 결과 설명</code> + CASE 54 <code>변경·승인 결과 안내</code> + CASE 55 <code>심사·판정 절차 안내</code> + CASE 56 <code>대기·지연 상태 안내</code>');
    expect(html).toContain('CASE 31 <code>후속 처리 안내</code> + CASE 32 <code>혜택·의무 안내</code> + CASE 33 <code>결과 불복·재심사 안내</code>');
    expect(html).toContain('CASE 4 KRDS/Figma handoff');
    expect(html).toContain('표 헤더만 바꾸고 끝내지 않고 Description, 기본 예시 문구, 숨은 레이블, <code>krds-lint</code> fixture를 같이 남깁니다.');
    expect(html).toContain('신청할 수 있는 사람 보기 / 발급되는 서류 확인 / 준비할 서류와 처리 시간 확인');
    expect(html).toContain('신청자격 / 발급서류 / 구비서류 / 처리기간 → 신청할 수 있는 사람 / 발급되는 서류 / 준비할 서류 / 처리까지 걸리는 시간');
    expect(html).toContain('D-9 비교 선택 연결: 정부24 <code>노인장기요양 등급 신청</code>은 CASE 34, 홈택스 <code>주택임대소득 분리과세 / 종합과세 선택</code>은 CASE 34, 대한민국법원 <code>소액사건심판 신청</code>은 CASE 34로 먼저 다시 이어 봅니다.');
    expect(html).toContain('절차 자체를 고르는 문제는 CASE 60으로 넘기고, 같은 선택 안의 비용·혜택 차이는 CASE 34 한 로그 행에서 같이 판정합니다.');
    expect(html).toContain('D-9 구조 규칙 연결: 정부24 <code>전입신고</code>와 홈택스 <code>사업자 등록 사항 정정 신청</code>은 CASE 18·58을 함께 붙여 먼저 다시 보고, 전자가족관계등록시스템 <code>가족관계등록부 정정</code>은 CASE 58에 우선 붙입니다. 대한민국법원 <code>집행문 부여 신청</code>은 보조 표본으로 CASE 18·58에 함께 기록합니다.');
    expect(html).toContain('채널 분기만 따로, 관할 안내만 따로 기록하지 말고 한 로그 행에서 같이 판정합니다.');
    expect(html).toContain('D-9 신청인 유형 연결: 정부24 <code>건강보험 피부양자 등록 신청</code>은 CASE 19, 홈택스 <code>연말정산 간소화</code>는 CASE 19, 대한민국법원 <code>소송 기록 열람·복사 신청</code>은 CASE 19로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 조건부 필수 연결: 정부24 <code>외국인등록번호</code>는 CASE 20, 홈택스 <code>영세율 신고</code>는 CASE 20, 대한민국법원 <code>협의이혼 의사확인 신청</code>은 CASE 20으로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 알림 채널 연결: 국민신문고 <code>이메일</code>은 CASE 21, 국세청 <code>전자고지(송달) 신청 및 해지</code>는 CASE 21, 전자소송포털 <code>민사 등 사건진행 알림서비스</code>는 CASE 21로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 증명서 종류 연결: 정부24 <code>주민등록등본 / 주민등록초본</code>은 CASE 22, 전자가족관계등록시스템 <code>일반증명서 / 상세증명서 / 특정증명서</code>는 CASE 22, 홈택스 <code>납세증명서 (일반용) / 납세증명서 (금융거래용)</code>는 CASE 22로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 공개 범위 연결: 정부24 <code>개인정보 제공 범위 선택</code>은 CASE 23, 대한민국법원 <code>말소 사항 포함 / 현행 / 특정 시점</code>은 CASE 23, 홈택스 <code>세무정보 열람권한 부여</code>는 CASE 23으로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 첨부 파일 연결: 정부24 <code>파일을 첨부하세요</code>는 CASE 24, 홈택스 <code>증빙서류 파일 첨부</code>는 CASE 24, 대한민국법원 <code>PDF 형식만 가능</code>은 CASE 24로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 절차 선택 연결: 국민신문고 <code>민원 유형 선택</code>은 CASE 60, 홈택스 <code>휴업·폐업 신고</code>는 CASE 60, 대한민국법원 <code>개인회생·파산</code>은 CASE 60으로 먼저 다시 이어 보고, <code>성년후견·한정후견·특정후견</code>은 보조 표본으로 CASE 60에 함께 기록합니다.');
    expect(html).toContain('절차 이름만 따로, 비교 링크만 따로 기록하지 말고 한 로그 행에서 같이 판정합니다.');
    expect(html).toContain('D-9 위임 권한 연결: 정부24 <code>병적증명서 발급</code>은 CASE 59, 홈택스 <code>세무대리인 수임 동의</code>는 CASE 38·11·59, 전자가족관계등록시스템 <code>소송 대리인 등록</code>은 CASE 59로 먼저 다시 이어 봅니다.');
    expect(html).toContain('동의만 따로, 권한 범위만 따로 기록하지 말고 한 로그 행에서 같이 판정합니다.');
    expect(html).toContain('D-9 예상 계산 연결: 정부24 <code>자동차 이전 등록 신청</code>은 CASE 35, 홈택스 <code>부동산 임대소득 신고</code>는 CASE 35, 대한민국법원 <code>인지대·송달료 계산</code>은 CASE 35로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 예상값 연결: 정부24 <code>건강보험료 경감 신청</code>은 CASE 36, 홈택스 <code>근로장려금 신청</code>은 CASE 36, 대한민국법원 <code>부동산 강제경매 신청</code>은 CASE 36으로 먼저 다시 이어 봅니다.');
    expect(html).toContain('예상값 기준 시점·변수·정산 경로가 먼저 보이는지 보고, 같은 과업에서 감액·환수·추징이 드러나면 CASE 41로 이어 판정합니다.');
    expect(html).toContain('D-9 결과 연결 CTA 연결: 정부24 <code>국민연금 가입 내역</code>은 CASE 37, 홈택스 <code>부가가치세 예정신고</code>는 CASE 37, 대한민국법원 <code>지급명령 신청</code>은 CASE 37로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 예상·정산 연결: 정부24 <code>기초연금 신청</code>은 CASE 41, 홈택스 <code>근로장려금 신청</code>은 CASE 41·42, 홈택스 <code>부가가치세 조기 환급</code>은 CASE 41, 대한민국법원 <code>부동산 강제경매 신청</code>은 CASE 41로 먼저 다시 이어 봅니다.');
    expect(html).toContain('예상값 화면만 따로 보지 말고 같은 과업의 확정 화면이 있으면 CASE 42까지 같은 라운드에서 이어 판정합니다.');
    expect(html).toContain('D-9 기간 제한 연결: 정부24 <code>농업직불금 신청</code>은 CASE 45, 홈택스 <code>반기납부 신청</code>은 CASE 45, 전자가족관계등록시스템 <code>국적 이탈 신고</code>는 CASE 45로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 유지 조건 연결: 정부24 <code>양육수당 신청</code>은 CASE 46, 홈택스 <code>간이과세자 부가세 신고</code>는 CASE 46, 전자가족관계등록시스템 <code>성년후견 종료 신청</code>은 CASE 46으로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 긴급 연결 연결: 정부24 <code>긴급복지지원 신청</code>은 CASE 47, 홈택스 <code>지방세 연계 납부</code>는 CASE 47, 대한민국법원 <code>친권 상실 청구</code>는 CASE 47로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 병행 절차 연결: 정부24 <code>소상공인 정책자금 신청</code>은 CASE 48, 홈택스 <code>지방세 연계 납부</code>는 CASE 48, 대한민국법원 <code>부재자 재산 관리인 선임 청구</code>는 CASE 48로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 상담·연락처 연결: 정부민원안내콜센터 <code>정부 민원 안내 110</code>은 CASE 50, 홈택스 <code>국세상담센터 126</code>은 CASE 50, 전자가족관계등록시스템 <code>사용자지원센터</code>는 CASE 50으로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 중대한 결정 연결: 정부24 <code>확정일자 신청</code>은 CASE 52, 홈택스 <code>현금영수증 발급</code>은 CASE 52, 대한민국법원 <code>상속포기 신고</code>는 CASE 52로 먼저 다시 이어 보고, <code>지급명령 신청</code>은 보조 표본으로 CASE 52에 함께 기록합니다.');
    expect(html).toContain('D-9 이용 불가 연결: 정부24 <code>정부24 점검 화면</code>은 CASE 25, 홈택스 <code>지방세 연계 납부</code>는 CASE 25, 대한민국법원 <code>전자소송 일시 오류</code>는 CASE 25로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 조회·열람 연결: 정부24 <code>안심상속 원스톱 서비스 신청</code>은 CASE 53, 홈택스 <code>금융정보 조회</code>는 CASE 53, 대한민국법원 <code>판결문 열람</code>는 CASE 53으로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 변경·승인 결과 연결: 정부24 <code>지방세 고지서 수령 방법 선택</code>은 CASE 54, 홈택스 <code>환급금 수령 계좌 등록/변경</code>는 CASE 54, 대한민국법원 <code>외국 판결 승인 신청 (이혼)</code>는 CASE 54로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 심사·판정 연결: 정부24 <code>장기요양인정 신청</code>은 CASE 55, 홈택스 <code>종합소득세 신고 도움</code>는 CASE 55, 대한민국법원 <code>개명 허가 신청</code>는 CASE 55로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 대기·지연 연결: 정부24 <code>온라인 민원 신청 진행 상태</code>는 CASE 56, 홈택스 <code>세금 환급금 조회</code>는 CASE 56, 전자가족관계등록시스템 <code>국적이탈 신고 완료</code>는 CASE 56으로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 복수 조건 연결: 정부24 <code>긴급복지지원 신청</code>은 CASE 57, 홈택스 <code>근로장려금 신청</code>은 CASE 57, 전자가족관계등록시스템 <code>국적 이탈 신고</code>는 CASE 57로 먼저 다시 이어 봅니다.');
    expect(html).toContain('D-9 실화면 연결: 정부24 <code>전입신고 완료</code>는 CASE 31, 홈택스 <code>국세 환급금 조회</code>는 CASE 42·CASE 32·CASE 56, 전자가족관계등록시스템 <code>전자 발급본 안내</code>는 CASE 27, 대한민국법원 <code>지급명령 이의신청</code>은 CASE 33으로 먼저 다시 이어 봅니다.');
    expect(html).toContain('실화면 1개를 새 CASE 1개로 바로 늘리지 말고, 기존 묶음에 먼저 붙인 뒤 빈 대표 사이트만 채웁니다.');
    expect(html).toContain('대표 사이트별 다음 우선 표본');
    expect(html).toContain('다음 순회 기준 화면');
    expect(html).toContain('이미 본문·사례 카드·KRDS 조합까지 한 번 묶인 화면도 <code>회귀 기준 표본</code>으로 같이 유지합니다.');
    expect(html).toContain('실제 직접 보강 우선순위는 바로 아래 <code>D-9-3</code> 표에서 따로 관리합니다.');
    expect(html).toContain('정부24');
    expect(html).toContain('CASE 4 <code>신청 상세</code>, CASE 31 <code>후속 처리 안내</code>, CASE 37 <code>결과 연결 CTA</code>');
    expect(html).toContain('<code>전입신고</code>, <code>사업자 등록 사항 정정 신청</code>, <code>안심상속 원스톱 서비스 신청</code>');
    expect(html).toContain('국민건강보험');
    expect(html).toContain('<code>질병명·병원 이름 검색</code>, <code>피부양자·산정특례 안내</code>, <code>보험료 산정</code>');
    expect(html).toContain('대한민국법원 (보조 표본)');
    expect(html).toContain('<code>상속포기 신고</code>, <code>지급명령 이의신청</code>, <code>개인회생·파산</code>');
    expect(html).toContain('화면 1개 + CASE 1묶음 + KRDS 조합 1개');
    expect(html).toContain('원칙별 남은 근거 공백');
    expect(html).toContain('<code>국민건강보험</code>, <code>고용24</code>, <code>서울특별시 응답소</code>');
    expect(html).toContain('<code>국민건강보험</code>, <code>고용24</code>, <code>서울특별시 응답소</code>, <code>전자가족관계등록시스템</code>의 상대적으로 얇았던 <code>2장 무번역</code>, <code>3장 정보핵심화</code>, <code>5장 표기법·맞춤법</code> 슬롯은 이미 <code>원칙 본문 + 사례 카드 + KRDS 조합</code>까지 한 번에 묶었습니다.');
    expect(html).toContain('<code>전자가족관계등록시스템</code>의 <code>국적 회복 허가 / 국적 이탈 신고</code>도 <code>2장·3장·4장·7장</code> 슬롯을 모두 직접 연결했으므로, 이제는 남은 공백이 아니라 회귀 기준 표본으로 유지합니다.');
    expect(html).toContain('따라서 이번 순회의 실질 보강 우선순위는 새 사이트를 더하기보다, 아래 표처럼 <code>4장 심리적안전망</code>과 <code>7장 컴포넌트 라이팅</code>에서 고위험 흐름과 KRDS 기본값을 더 직접 연결하는 데 둡니다.');
    expect(html).toContain('<strong>4장 심리적안전망</strong>');
    expect(html).toContain('<code>실업인정 인터넷 신청</code>, <code>질의응답·답변원문</code>, <code>결과보기</code>');
    expect(html).toContain('<strong>7장 컴포넌트 라이팅</strong>');
    expect(html).toContain('<code>질병명·병원 이름 검색</code>, <code>훈련 검색</code>, <code>민원 신청하기 / 결과보기</code>');
    expect(html).toContain('<code>Description / 기본 예시 문구 / 숨은 레이블 메모</code>');
    expect(html).toContain('<strong>2장·3장·5장 운영 메모</strong>');
    expect(html).toContain('<code>피부양자·산정특례 안내</code>, <code>조기재취업수당 안내</code>, <code>실업인정 인터넷 신청</code>, <code>질의응답·답변원문</code>, <code>결과보기</code>, <code>보험료 산정</code>, <code>국적 회복 허가</code>, <code>국적 이탈 신고</code>는 더 이상 남은 공백 표에 두지 않고, 2장 무번역·3장 정보핵심화 직접화 섹션, 5장 <code>상대적으로 얇은 대표 사이트 표기 직접화</code>, 7장 Description·숨은 레이블·<code>krds-lint</code> 회귀 대상으로 유지합니다.');
    expect(html).not.toContain('<strong>5장 표기법·맞춤법</strong></td><td style="padding:10px 12px;border:1px solid var(--color-border-light);">국민건강보험, 서울특별시 응답소, 고용24</td><td style="padding:10px 12px;border:1px solid var(--color-border-light);"><code>질병명·병원 이름 검색</code>, <code>질의응답·답변원문</code>, <code>실업인정 인터넷 신청</code></td><td style="padding:10px 12px;border:1px solid var(--color-border-light);"><code>질병명·병원 이름</code>, <code>답변예정일</code>, <code>실업인정일</code> 같은 표기가 띄어쓰기, 상태 레이블, 날짜·단위까지 시민 언어 리듬으로 읽히는가?</td><td style="padding:10px 12px;border:1px solid var(--color-border-light);">CASE 10 / CASE 5 / CASE 8</td><td style="padding:10px 12px;border:1px solid var(--color-border-light);">Search + Badge + Table + Linter</td></tr>');
    expect(html).toContain('피부양자 취득·상실 여부와 산정특례 적용 대상 여부를 확인한 뒤 보험료 산정 내역을 조회하시기 바랍니다.');
    expect(html).toContain('중증질환 본인부담 감면 대상인지 먼저 확인해 보세요.');
    expect(html).toContain('이번 달 건강보험료가 어떻게 계산됐는지 확인할 수 있습니다.');
    expect(html).toContain('변동이 있다면 [변동 신고], 부담이 크다면 [경감 신청 자가 진단], 퇴직 뒤라면 [임의계속가입 확인]으로 이어집니다.');
    expect(html).toContain('복지로, 국민건강보험, 전자가족관계등록시스템');
    expect(html).toContain('국적 회복 허가');
    expect(html).toContain('국적 이탈 신고');
    expect(html).toContain('한국 국적 다시 받기 허가 결과인지 먼저 보여주고,');
    expect(html).toContain('허가 뒤 1년 내 외국 국적 포기 절차와 외국국적불행사서약 대상 여부를 바로 설명합니다.');
    expect(html).toContain('국적 이탈 신고인지도 첫 줄에서 풀어 쓰고,');
    expect(html).toContain('복수 국적·병역·기한 요건을 먼저 확인한 뒤 [요건 확인]으로 이어집니다.');
    expect(html).toContain('허가 결과 뒤 [신고 방법 보기], 신고 전 [요건 확인]이 같은 첫 블록에 함께 있어야 합니다.');
    expect(html).toContain('CASE 2 KRDS/Figma handoff');
    expect(html).toContain('부양가족 등록·해제 대상, 중증질환 본인부담 감면 대상, 이번 달 보험료 계산 기준, 한국 국적 다시 받기 허가 결과, 1년 내 외국 국적 포기, 외국국적불행사서약 대상 여부, 외국 국적 포기 증명서 제출 경로, 변동 신고·요건 확인·신고 방법 CTA를 함께 적습니다.');
    expect(html).toContain('부양가족으로 등록하거나 해제할 가족인지 먼저 확인해 주세요 / 중증질환 본인부담 감면 대상인지 확인 / 이번 달 보험료 계산 기준 보기 / 한국 국적 다시 받기 허가 결과를 먼저 확인해 주세요 / 1년 내 외국 국적 포기와 외국국적불행사서약 대상 여부를 확인해 주세요 / 외국 국적 포기 증명서 제출 경로 확인 / 신고 방법 보기');
    expect(html).toContain('부양가족 등록·해제 대상 확인하기 / 중증질환 본인부담 감면 요건 보기 / 현재 보험료 계산 기준 보기 / 보험료 변동 신고하기 / 보험료 경감 신청 가능 여부 자가 진단하기 / 퇴직 뒤 예전 직장 보험료 계속 가입 확인하기 / 국적 회복 허가 결과 확인하기 / 외국 국적 포기 기한과 서약 대상 확인하기 / 외국 국적 포기 증명서 제출 경로 확인하기 / 국적 신고 방법 보기');
    expect(html).toContain('부양가족·감면·보험료 계산과 국적 허가·신고·기한·요건 확인이 각각 첫 블록에서 끊기지 않고, 시민 언어 헤더 뒤에 공식 용어와 다음 CTA가 바로 이어지는지 확인합니다.');
    expect(html).toContain('국민건강보험처럼 "피부양자", "산정특례", "보험료 산정"이 한 줄에 붙는 화면도 같습니다.');
    expect(html).toContain('전자가족관계등록시스템처럼 "국적 회복 허가", "국적 이탈 신고"가 첫 줄에 남는 화면도 같습니다.');
    expect(html).toContain('특히 한국 국적을 다시 받는 일인지, 국적 이탈 신고인지, 허가 뒤 1년 내 외국 국적 포기와 외국국적불행사서약 대상 여부를 어떻게 확인하는지, 복수 국적·병역 요건이 있는지를 첫 블록에서 같이 알아야 합니다.');
    expect(html).toContain('원문 3개 + 원칙 장 2개 이상 + CASE 1묶음 + KRDS 조합 1개');
    expect(html).toContain('상대적으로 얇은 대표 사이트 공식 재검산 메모');
    expect(html).toContain('초기에는 <code>국민건강보험</code>, <code>고용24</code>, <code>서울특별시 응답소</code>가 상대적으로 얇았고, 이번 정렬에서는 <code>전자가족관계등록시스템</code>의 국적 화면도 <code>2장·3장·4장·7장</code>까지 같은 공식 재검산 표에서 관리합니다.');
    expect(html).toContain('<code>질병명 / 병원 이름</code>, <code>피부양자</code>, <code>산정특례</code>, <code>보험료 산정</code>');
    expect(html).toContain('<code>실업인정일</code>, <code>적극적인 재취업활동</code>, <code>조기재취업수당</code>, <code>훈련 검색</code>');
    expect(html).toContain('<code>처리기관</code>, <code>답변예정일</code>, <code>답변원문</code>, <code>결과보기</code>');
    expect(html).toContain('<strong>전자가족관계등록시스템</strong></td><td style="padding:10px 12px;border:1px solid var(--color-border-light);"><code>국적 회복 허가</code>, <code>국적 이탈 신고</code></td><td style="padding:10px 12px;border:1px solid var(--color-border-light);"><code>국적 회복 허가</code>, <code>국적 이탈 신고</code>, <code>1년 내 외국 국적 포기</code>, <code>외국국적불행사서약 대상 여부</code>, <code>[요건 확인]</code></td>');
    expect(html).toContain('<strong>전자가족관계등록시스템 승격 메모</strong>');
    expect(html).toContain('<code>국적 회복 허가</code>, <code>국적 이탈 신고</code>는 별도 보조 노트로 두지 않고 위 공식 재검산 표의 정식 행에서 <code>첫 레이블 + 후속 의무 + 기한 + 후속 제출 의무 + CTA</code>를 함께 관리합니다.');
    expect(html).toContain('4장 D-9-3과 7장 D-6-5에도 <code>한국 국적 다시 받기 허가 결과 → 1년 내 외국 국적 포기 → 외국국적불행사서약 대상 여부 → 외국 국적 포기 증명서 제출 경로</code>, <code>국적 이탈 가능 기한 → 병역 조건 → 기한 경과 뒤 상태</code>, <code>신고 방법 보기 / 요건 확인</code>를 같은 문장으로 내려 같은 회귀 기준으로 유지합니다.');
    expect(html).toContain('용어 1개');
    expect(html).toContain('이 네 사이트는 <code>용어 1개</code>만 따로 올리지 않습니다.');
    expect(html).toContain('원문 3개 + 상태·날짜 또는 입력 범위 1개 + CTA 1개 + KRDS 조합 1개');
    expect(html).toContain('대표 사이트 4개에서 다시 확인한 검색·제도 안내·결과 재확인·허가 뒤 후속 의무 패턴을 Description, 기본 예시 문구, 숨은 레이블까지 바로 옮길 수 있게 같은 형식으로 남깁니다.');
    expect(html).toContain('<code>전자가족관계등록시스템</code>의 <code>국적 회복 허가 / 국적 이탈 신고</code>도 <code>2장·3장·4장·7장</code> 슬롯을 모두 직접 연결했으므로, 이제는 남은 공백이 아니라 회귀 기준 표본으로 유지합니다.');
    expect(html).not.toContain('<strong>2장 무번역</strong></td><td style="padding:10px 12px;border:1px solid var(--color-border-light);">전자가족관계등록시스템</td><td style="padding:10px 12px;border:1px solid var(--color-border-light);"><code>국적 회복 허가</code>, <code>국적 이탈 신고</code></td>');
    expect(html).not.toContain('<strong>3장 정보핵심화</strong></td><td style="padding:10px 12px;border:1px solid var(--color-border-light);">전자가족관계등록시스템</td><td style="padding:10px 12px;border:1px solid var(--color-border-light);"><code>국적 회복 허가</code></td>');
    expect(html).toContain('<strong>4장 심리적안전망</strong></td><td style="padding:10px 12px;border:1px solid var(--color-border-light);">전자가족관계등록시스템</td><td style="padding:10px 12px;border:1px solid var(--color-border-light);"><code>국적 회복 허가</code>, <code>국적 이탈 신고</code></td>');
    expect(html).toContain('<strong>7장 컴포넌트 라이팅</strong></td><td style="padding:10px 12px;border:1px solid var(--color-border-light);">전자가족관계등록시스템</td><td style="padding:10px 12px;border:1px solid var(--color-border-light);"><code>국적 회복 허가</code>, <code>국적 이탈 신고</code></td>');
    expect(html).toContain('<strong>회귀 규칙</strong>');
    expect(html).toContain('한 화면을 다시 볼 때도 <code>원문 3개 + 원칙 장 2개 이상 + CASE 1묶음 + KRDS 조합 1개</code>를 같은 로그 행에 남깁니다. 이미 메운 2장·3장·5장 슬롯은 회귀 기준으로 유지하고, 4장은 위험·복구 경로, 7장은 <code>Description / 기본 예시 문구 / 숨은 레이블 메모</code>까지 한 라운드에서 함께 내려가는지 확인합니다.');
    expect(html).toContain('신청 상세 헤더: <code>신청자격 / 구비서류 / 처리기간</code>이 <code>신청할 수 있는 사람 / 준비할 서류 / 처리까지 걸리는 시간</code>처럼 첫 표에서 바로 이해되는지 확인합니다.');
    expect(html).toContain('상태표 요약: <code>담당 기관에서 답변을 준비하고 있습니다</code>, <code>답변 예정일 2026.06.12</code>, <code>나의 민원에서 다시 확인</code>이 표 위 첫 영역에 함께 있는지 확인합니다.');
    expect(html).toContain('<code>답변원문</code>이 등록되면 <code>결과보기</code>에서 바로 확인할 수 있습니다.');
    expect(html).toContain('같은 건의 재확인이 아니라면 <code>민원 신청하기</code>를 별도 버튼으로 둡니다.');
    expect(html).toContain('발급 결과 재확인: <code>금융기관 제출용 납세증명서 — 발급일 기준 30일</code>, <code>발급 후 90일 내 저장해 두세요</code>, <code>문서확인번호 / QR코드 / 증명서 진위확인</code>, <code>전자 발급본이 공문서와 동일한 효력</code>이 같은 첫 블록에 모이는지 확인합니다.');
    expect(html).toContain('원문 3개 + 상태 요약 1문장 + 효력 또는 유효기간 1개 + 재확인 CTA 1개 + KRDS 조합 1개');
    expect(html).toContain('상태·결과 묶음 바로 판정표');
    expect(html).toContain('상태 첫 줄: <code>환급세액 420,000원 — 전년보다 180,000원 줄었습니다</code>, <code>승인 확정 시 국내 이혼 효력 발생</code>, <code>현재 단계: 담당 기관 검토 중</code>처럼 지금 결과나 단계를 첫 줄에서 바로 이해할 수 있는지 확인합니다.');
    expect(html).toContain('예정일·남은 기간: <code>5월 31일까지</code>, <code>다음 부과분부터</code>, <code>법원 심사 1~3개월</code>, <code>예상 입금일 [예정일]</code>, <code>최대 6개월</code>처럼 기한·효력 발생 시점·대기 기간이 같은 첫 블록에 붙어 있는지 확인합니다.');
    expect(html).toContain('다음 행동·문의/재확인: <code>[바로 납부하기]</code>, <code>[국내 집행 방법]</code>, <code>[불복 방법]</code>, <code>[처리 현황 조회]</code>, <code>[계좌 등록하기]</code>, <code>기한이 지나면 문의</code>처럼 행동·문의 경로가 함께 남는지 확인합니다.');
    expect(html).toContain('서울특별시 응답소 재확인 화면: <code>담당 기관에서 답변을 준비하고 있습니다</code>, <code>답변 예정일 2026.06.12</code>, <code>나의 민원에서 다시 확인</code>, <code>같은 건이 아니면 새 민원 신청하기</code>가 같은 첫 블록에 붙는지 추가로 봅니다.');
    expect(html).toContain('원문 3개 + 상태 1문장 + 예정일 또는 남은 기간 1개 + 다음 CTA 또는 문의 경로 1개 + KRDS 조합 1개');
    expect(html).toContain('결과 뒤 후속 흐름 묶음 바로 판정표');
    expect(html).toContain('후속 행동: <code>주소 변경이 완료됐습니다</code>, <code>자동 반영: 국민연금·건강보험 / 별도 변경: 자동차등록·금융기관</code>, <code>1개월 이내 주민센터 신고</code>처럼 다음 행동·연계 기관·기한이 같은 첫 블록에 붙어 있는지 확인합니다.');
    expect(html).toContain('자동·별도: <code>장애 정도가 결정됐습니다</code>, <code>지금 신청 가능한 혜택</code>, <code>1년 내 외국 국적 포기와 서약 대상 여부 별도 확인</code>, <code>1년 내 포기나 서약 절차를 마치지 않으면 회복한 대한민국 국적을 다시 잃을 수 있습니다</code>처럼 자동 적용과 별도 신청·신고가 한 줄에서 구분되는지 확인합니다.');
    expect(html).toContain('불복 기한·권리구제: <code>결과에 이의가 있다면</code>, <code>심사 청구 가능</code>, <code>이의신청·심판청구 가능</code>, <code>90일 이내</code>, <code>2주 이내</code>, <code>민사소송 전환</code>처럼 권리구제 가능 여부와 다음 절차가 함께 남는지 확인합니다.');
    expect(html).toContain('원문 3개 + 후속 행동 1개 + 자동/별도 1개 + 기한 또는 권리구제 1개 + KRDS 조합 1개');
    expect(html).toContain('실패 패턴 + 바꿀 문장 + KRDS 조합');
    expect(html).toContain('확정일자 / 상속포기처럼 효력·기한·취소 불가·대안 비교가 한 번에 얽히면 중대한 결정 안내 사례 카드로 먼저 올립니다.');
    expect(html).toContain('지급명령 신청 / 이행권고결정도 2주 이의 기간, 소송 전환, 확정 효력이 먼저 보여야 하므로 같은 중대한 결정 안내 패턴으로 흡수합니다.');
    expect(html).toContain('장기요양인정 / 개명 허가처럼 누가 어떤 기준으로 언제 결정하는지가 핵심이면 심사·판정 절차 안내로 묶습니다.');
    expect(html).toContain('전자가족관계등록시스템 국적 회복 허가 / 국적 이탈 신고처럼 허가 뒤 외국 국적 포기 절차, 외국국적불행사서약 대상 여부, 1년 내 기한, 외국 국적 포기 증명서 제출 경로, 복수 국적·병역 조건이 함께 걸리면 CASE 32·45·46·57 묶음으로 먼저 흡수합니다.');
    expect(html).toContain('KRDS에서는 Result page, Notice banner, Checklist, Button을 같이 봅니다.');
    expect(html).toContain('전입신고 완료 / 장애 정도 결정 / 지급명령 이의신청처럼 결과 직후 후속 행동·자동/별도·불복 기한을 함께 판단해야 하면 결과 뒤 후속 흐름 묶음으로 먼저 봅니다.');
    expect(html).toContain('협의이혼 의사확인처럼 사람·서류·기간이 동시에 맞아야 하면 복수 조건 체크리스트로 묶고, 추가 입력이 뒤늦게 나타나면 조건부 필수 항목 예시로 이어 붙입니다.');
    expect(html).toContain('진정 / 청원 / 제안 / 신고, 휴업·폐업, 개인회생·파산처럼 서비스 이름보다 내 상황에 맞는 절차 기준이 먼저 필요하면 절차 선택 안내로 묶습니다. KRDS에서는 Radio, Segmented control, Structured list, Helper text, Notice banner, Link를 같이 봅니다.');
    expect(html).toContain('부동산 거래 신고 / 공동사업장 등록 / 협의이혼 의사확인처럼 함께 신청해야 하는 사람과 추가 조건이 동시에 바뀌면 새 패턴으로 분리하지 않고 신청인 유형별 추가 서류, 복수 조건 체크리스트 예시로 흡수합니다. KRDS에서는 Fieldset, Radio, Helper text, Structured list, Notice banner를 같이 봅니다.');
    expect(html).toContain('전입신고 / 사업자 등록 사항 정정 신청 / 가족관계등록부 정정처럼 온라인 가능 여부와 관할 기관이 동시에 갈리면 새 패턴으로 분리하지 않고 온라인/방문 분기와 담당 기관·관할 안내를 같은 화면에서 함께 씁니다. KRDS에서는 Radio, Helper text, Structured list, Badge, Button을 같이 봅니다.');
    expect(html).toContain('용어 1개가 원칙 1개를 뜻하지는 않습니다.');
    expect(html).toContain('관찰 사이트');
    expect(html).toContain('KRDS 컴포넌트');
    expect(html).toContain('복지로 자격 계산 — 계산식 용어를 도움말로 내리기');
    expect(html).toContain('고용24 실업인정 — 해야 할 행동과 날짜를 먼저');
    expect(html).toContain('공공서비스 CTA — 과업별로 버튼을 나누기');
    expect(html).toContain('홈택스 메뉴 이름 — 제도명보다 지금 할 일을 먼저 보여주기');
    expect(html).toContain('복수 과업 메뉴 — 서로 다른 행동을 한 이름에 묶지 않기');
    expect(html).toContain('예상과 확정 차이 안내 — 바뀐 이유·차액 처리·정정 경로를 먼저 보여주기');
    expect(html).toContain('확정 결과 설명 — 산출 근거·증감 이유·다음 행동을 먼저 보여주기');
    expect(html).toContain('납부 방식 안내 — 일시납·분납·연납의 조건·기한·불이익을 먼저 보여주기');
    expect(html).toContain('이용권·포인트 사용 안내 — 사용 가능 항목·유효 기간·소멸·환수 위험을 먼저 보여주기');
    expect(html).toContain('기간 제한 서비스 안내 — 신청 가능 기간·마감 후 구제·다음 주기를 먼저 보여주기');
    expect(html).toContain('유지 조건 안내 — 계속 받는 조건·자동 종료·전환 경로를 먼저 보여주기');
    expect(html).toContain('긴급 연결 안내 — 즉시 도움 경로와 온라인 다음 절차를 먼저 보여주기');
    expect(html).toContain('병행 절차 안내 — 같이 해야 하는 외부 절차와 복귀 경로를 먼저 보여주기');
    expect(html).toContain('탐색 레이블 정리 — 공백 없는 복합어를 풀고 클릭 전 의미를 먼저 보여주기');
    expect(html).toContain('상담·연락처 안내 — 채널, 대상, 운영시간, 비용을 한 자리에서 보여주기');
    expect(html).toContain('접근성 레이블 정리 — 번호·이동·새창만 남기지 않고 목적과 상태를 먼저 들려주기');
    expect(html).toContain('중대한 결정 안내 — 효력·기한·되돌릴 수 없는 결과·대안을 먼저 보여주기');
    expect(html).toContain('조회·열람 범위 안내 — 포함·제외 항목과 별도 확인 경로를 먼저 보여주기');
    expect(html).toContain('변경·승인 결과 안내 — 어디에 언제 반영되고 무엇은 별도인지 먼저 보여주기');
    expect(html).toContain('검색창 — 검색어와 다음 행동을 같이 보여주기');
    expect(html).toContain('동의 화면 — 약관보다 이유와 범위를 먼저 보여주기');
    expect(html).toContain('비회원 이용·회원가입 — 필요한 인증과 가능한 작업을 먼저 보여주기');
    expect(html).toContain('재발급 화면 — 제출 기준 기간과 다음 절차를 먼저 보여주기');
    expect(html).toContain('신청 분기 — 준비 서류·처리 기간·수령 방법을 먼저 보여주기');
    expect(html).toContain('완료 화면 — 접수번호·다음 일정·확인 경로를 같이 보여주기');
    expect(html).toContain('세션 종료 흐름 — 임시 저장과 재진입 경로를 같이 보여주기');
    expect(html).toContain('기한 임박 경고 — 남은 기간과 지금 행동을 먼저 보여주기');
    expect(html).toContain('온라인/방문 분기 — 가능한 경로와 준비물을 먼저 보여주기');
    expect(html).toContain('신청인 유형 분기 — 본인·가족·이해관계인별 추가 서류를 먼저 보여주기');
    expect(html).toContain('조건부 필수 항목 — 선택한 답 때문에 필요한 입력·첨부를 바로 보여주기');
    expect(html).toContain('알림 채널별 수신 내용 — 채널별로 무엇이 언제 오는지 먼저 보여주기');
    expect(html).toContain('Checkbox, Radio, Helper text, Notice banner, Structured list, Result page, Link');
    expect(html).toContain('증명서 종류 선택 — 포함 정보와 제출처를 먼저 보여주기');
    expect(html).toContain('검색어 전체 삭제');
    expect(html).toContain('민원 결과보기');
    expect(html).toContain('전체 동의 (필수 2개, 선택 1개)');
    expect(html).toContain('공개 정보 목록 보기');
    expect(html).toContain('비회원으로 이용하기 (일부 서비스만 가능)');
    expect(html).toContain('공동인증서 / 금융인증서');
    expect(html).toContain('발급 후 90일 내 저장해 두세요');
    expect(html).toContain('납세증명서는 발급일 기준 30일 / 가족관계증명서는 제출처 최근 발급 기준 확인');
    expect(html).toContain('긴급 발급 (3~5일, 방문 수령, 기존 여권 지참)');
    expect(html).toContain('질병·재해 사유 + 진단서·피해 확인서 + 처리 10일 내');
    expect(html).toContain('공탁금과 이자 함께 청구');
    expect(html).toContain('답변이 등록되면 나의 민원에서 접수번호로 다시 확인할 수 있습니다.');
    expect(html).toContain('서류명 또는 업무명 / 질병명 또는 병원 이름');
    expect(html).toContain('원하는 병원이 없다면 병원 이름 일부나 질병명으로 다시 검색하고, 고용24는 과정명 대신 배우고 싶은 기술·자격증·직무로 다시 찾습니다. 복지로는 지역명·제도 이름으로 다시 찾아봅니다.');
    expect(html).toContain('국민건강보험 검색은 병원 이름 일부나 질병명으로 다시 찾고, 검색 뒤 <code>보험료 산정</code> 결과는 계산 기준 보기로 이어집니다.');
    expect(html).toContain('배우고 싶은 기술·자격증 또는 훈련 이름');
    expect(html).toContain('고용24는 과정명 대신 배우고 싶은 기술·자격증·직무로 다시 찾습니다.');
    expect(html).toContain('고용24 훈련 검색은 결과 카드에서 <code>훈련 일정 보기</code>, <code>신청 조건 보기</code>처럼 다음 행동이 바로 이어져야 합니다.');
    expect(html).toContain('배우고 싶은 기술이나 자격증으로 훈련을 찾아보세요');
    expect(html).toContain('나의 민원 확인하기');
    expect(html).toContain('지금 납부하기');
    expect(html).toContain('장기미환급금 찾기 서비스 / 국세환급금 계좌신고 / 세법해석 사전답변 신청');
    expect(html).toContain('나의 세무대리인 해임 / 근로소득 원천징수영수증 / 종합소득세 중간예납');
    expect(html).toContain('못 받은 세금 환급금 조회·신청');
    expect(html).toContain('세금 환급받을 계좌 등록');
    expect(html).toContain('세법 적용 결과 미리 확인 신청');
    expect(html).toContain('세무대리인 위임 취소');
    expect(html).toContain('급여에서 공제된 세금 확인서 (원천징수영수증)');
    expect(html).toContain('11월 소득세 선납 (중간예납) — 대상인지 먼저 확인하세요');
    expect(html).toContain('전자고지(송달) 신청 및 해지');
    expect(html).toContain('지급명세서 제출·수정·삭제');
    expect(html).toContain('현금영수증 발급·취소·수정');
    expect(html).toContain('국선대리인 신청(불복청구서 제출전)/(제출후)');
    expect(html).toContain('대한민국법원의 <code>국선대리인 신청(불복청구서 제출전)/(제출후)</code>도 제출 단계 선택을 괄호 뒤에 숨깁니다.');
    expect(html).toContain('관찰 사이트</strong> 홈택스, 대한민국법원');
    expect(html).toContain('전자 고지서 설정 → 전자 고지서 받기 / 우편으로 다시 받기');
    expect(html).toContain('국세청 전자송달은 신청한 날의 다음 날부터 효력이 생기고, 전자우편주소 또는 전화번호로 발송 사실을 알립니다.');
    expect(html).toContain('납부기한까지 3회 이상 열어보지 않으면 전자송달이 자동 종료되어 종이 고지서가 다시 발송되므로');
    expect(html).toContain('세금계산서 / 계산서');
    expect(html).toContain('기초연금 신청');
    expect(html).toContain('부가가치세 조기 환급');
    expect(html).toContain('배우자도 기초연금을 받으면 두 분 모두 20% 감액됩니다. 국민연금 수령액이 많으면 추가 감액될 수 있습니다. 소득·재산이 바뀌면 [변동 신고], 미신고 시 과거 수령액 환수 가능');
    expect(html).toContain('조기 환급은 신고 후 15일 이내 처리 예정입니다. 다만 요건 확인에서 제외되면 환급액이 줄거나 전액 추징될 수 있습니다. 기한을 넘기면 [환급 지연 이자 안내]');
    expect(html).toContain('예상 배당액은 확정 전 안내용입니다. 선순위 채권·임차인 보증금·집행 비용이 확정되면 실제 배당액이 달라질 수 있습니다. 취하 시 미사용 예납금만 환급됩니다 [배당 순위 확인] [예납금 환급 기준]');
    expect(html).toContain('건강보험 지역가입자 보험료');
    expect(html).toContain('관찰 사이트</strong> 국민건강보험, 홈택스');
    expect(html).toContain('이번 달 보험료에 적용됐고, 소득·재산이 바뀌면 [변동 신고]');
    expect(html).toContain('환급세액 420,000원 — 전년보다 180,000원 줄었습니다. 교육비 공제 감소 / 의료비 누락 가능 / 중도 입사분 반영. 추가 납부가 생기면 5월 31일까지 [바로 납부하기], 누락 내역은 [공제 내역 보기] [수정 신고 안내]');
    expect(html).toContain('본세 2,000,000원 + 신고 지연 45일 × 일일 0.022% = 가산세 19,800원. 자진신고 시 50% 감면 가능 [감면 조건 확인] [지금 자진신고하기]');
    expect(html).toContain('환급금 120,000원 — 연말정산 과납으로 발생 / 체납 세금 20,000원 먼저 충당 / 잔액 100,000원 입금 예정. 환급 계좌가 없으면 [계좌 등록하기], 30일 넘게 지연되면 [환급 지연 이자 안내]');
    expect(html).toContain('국세청 <code>원클릭 환급신고</code>와 <code>국세환급금 찾기</code>는 최근 5년 환급금과 환급계좌개설 신고 여부를 같이 확인하게 합니다.');
    expect(html).toContain('결과 숫자 아래에 산출 기준, 적용 시점, 변동 신고·부담 완화 CTA를 함께 고정해 보험료 결과가 설명과 행동으로 바로 이어지게 합니다.');
    expect(html).toContain('결과 숫자, 산출 기준, 적용 시점, 변동 신고·경감 신청·임의계속가입 CTA를 함께 적습니다.');
    expect(html).toContain('대표 예시는 국민건강보험처럼 이번 달 보험료, 계산 기준, 다음 부과 반영 시점, 변동 신고·경감 신청·임의계속가입 순서로 적습니다.');
    expect(html).toContain('이번 달 보험료를 먼저 확인해 주세요 / 계산 기준과 적용 시점 보기 / 경감 신청 또는 임의계속가입 확인');
    expect(html).toContain('이번 달 보험료를 먼저 확인해 주세요 / 계산 기준과 적용 시점 보기 / 경감 신청 또는 임의계속가입 확인 / 다음 부과 반영 시점 확인');
    expect(html).toContain('현재 보험료와 계산 기준 보기 / 보험료 변동 신고하기 / 보험료 경감 신청 가능 여부 확인하기 / 퇴직 뒤 예전 직장 보험료 계속 가입 확인하기');
    expect(html).toContain('현재 보험료와 계산 기준 보기 / 보험료 변동 신고하기 / 보험료 경감 신청 가능 여부 확인하기 / 퇴직 뒤 예전 직장 보험료 계속 가입 확인하기 / 다음 부과 반영 시점 확인하기');
    expect(html).toContain('결과 숫자, 산출 기준, 적용 시점, 부담될 때 갈 수 있는 CTA가 첫 결과 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('특히 이번 달 보험료, 계산 기준, 다음 부과 반영 시점, 변동 신고·경감 신청·임의계속가입 CTA가 첫 결과 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('연납(1월): 연간 세금의 9.15% 할인 / 분기 납부(6월·12월): 할인 없음 / 카드 무이자 할부 가능 [연납 신청] [카드사 확인]');
    expect(html).toContain('30만 원 이상이면 최대 12개월 분납 가능. 기한 내 미납 시 3% 가산금, 이후 매월 1.2% 추가. [분납 신청 바로가기]');
    expect(html).toContain('납부세액 1천만 원 초과 시 5월 31일까지 절반, 나머지는 7월 31일까지 납부할 수 있습니다. 이자 없음 [분납 선택] [대상 확인]');
    expect(html).toContain('매각허가결정 확정 후 통상 1개월 이내 전액 일시 납부해야 합니다. 분납 불가, 기한 내 미납 시 낙찰 취소 및 입찰보증금 몰수 [납부 계좌 확인] [영수증 안내]');
    expect(html).toContain('첫만남이용권 신청');
    expect(html).toContain('사용 가능 — 산후조리원·병원·약국·아동 물품. 사용 불가 — 식료품·의류·전자기기 [전체 목록 →]. 사용 기한: 출생일로부터 1년, 미사용 잔액은 소멸 [국민행복카드 잔액 확인]');
    expect(html).toContain('단태아·다태아별 지원 금액과 사용 기한을 먼저 보여주고, 요양기관에서만 사용할 수 있다는 점과 사용 불가 항목을 함께 알려줍니다 [사용 가능 기관 보기]');
    expect(html).toContain('장애인·노인·아동·산모 서비스별 월 이용 한도와 본인 부담이 다릅니다. 잔액 이월 가능 여부와 제공기관 등급을 먼저 확인하세요 [내 서비스 한도 확인]');
    expect(html).toContain('사용 가능한 혜택, 소멸 예정 포인트, 사용 신청 경로를 먼저 보여줍니다. 포인트 적립 기준과 유효 기간도 같은 화면에서 확인하세요 [사용 가능 혜택 보기] [포인트 사용 신청]');
    expect(html).toContain('신청 마감: 3월 31일. 기간이 끝나면 온라인 신청이 닫힙니다. 다음 신청 주기와 예외 신청 가능 여부는 [담당 기관 문의]');
    expect(html).toContain('반기납부 신청 기간: 1월 1~15일, 7월 1~15일. 이번 기간을 놓치면 다음 반기까지 기다려야 합니다. [신청 일정 보기]');
    expect(html).toContain('국세청은 원천세 반기별납부를 소득 지급일이 속하는 반기(1월~6월, 7월~12월)의 다음 달 10일까지 신고·납부하는 흐름으로 안내합니다.');
    expect(html).toContain('상반기 지급분은 7월 10일까지, 하반기 지급분은 다음 해 1월 10일까지');
    expect(html).toContain('국적 이탈은 만 18세가 되는 해 3월 31일까지 가능합니다. 기한을 넘기면 원칙적으로 병역 이행 또는 면제 후에만 가능하며, 예외적 국적이탈허가 대상은 별도 확인해 주세요. [요건 확인]');
    expect(html).toContain('전자가족관계등록시스템의 `국적 이탈 신고`는 기한 제한과 기한 경과 후 조건 변화를 화면 첫머리에서 분명하게 보여주지 않습니다.');
    expect(html).toContain('어린이집·유치원을 이용 중이면 양육수당을 받을 수 없습니다. 어린이집을 그만뒀다면 다음 달 말일까지 양육수당으로 전환 신청하세요. 만 86개월 또는 초등학교 입학 시 자동 종료됩니다. [전환 신청]');
    expect(html).toContain('전년도 매출이 8,000만 원 이상이면 올해 7월부터 일반과세자로 자동 전환됩니다. 전환 뒤에는 세금계산서 발행 의무가 생깁니다. [전환 기준 확인]');
    expect(html).toContain('피후견인 사망 시 후견은 자동 종료됩니다. 능력 회복으로 종료하려면 종료 심판을 신청하고, 종료 뒤 30일 이내 재산 목록과 후견 종료 보고서를 제출해야 합니다. [종료 절차 보기]');
    expect(html).toContain('AFTER — 유지 조건 + 자동 종료·전환 + 허가 뒤 의무 + 지금 준비할 일을 한 자리에서');
    expect(html).toContain('국적 회복이 허가돼도 끝나지 않습니다. 국적 취득일(회복 허가일)부터 1년 내 외국 국적 포기 절차를 진행해야 하며, 외국국적불행사서약 대상이면 서약으로 갈 수 있습니다. 외국 국적을 포기했다면 포기 증명서를 제출해야 합니다. [신고 방법 보기]');
    expect(html).toContain('전자가족관계등록시스템의 `성년후견 종료 신청`과 `국적 회복 허가`는 종료·미이행 뒤 법적 상태 변화와 후속 제출 기한이 흩어져 있습니다.');
    expect(html).toContain('긴급 연결 안내 — 즉시 도움 경로와 온라인 다음 절차를 먼저 보여주기');
    expect(html).toContain('지금 당장 위기 상황이라면 129 또는 가까운 주민센터로 먼저 도움을 요청하세요. 온라인에서는 지원 대상과 신청 항목을 이어서 확인할 수 있습니다');
    expect(html).toContain('국세 납부가 끝나도 지방소득세는 위택스에서 별도로 내야 합니다. 연계 오류가 나면 납부 처리 상태를 먼저 확인한 뒤 위택스로 이동해 주세요');
    expect(html).toContain('아동이 지금 위험하다면 법원 신청보다 먼저 112 또는 1577-1391로 연락하세요. 보호 조치 후 친권 상실·일시 정지 절차를 이어서 신청할 수 있습니다');
    expect(html).toContain('CASE 48: 병행 절차 안내 — 같이 해야 하는 외부 절차와 복귀 경로를 먼저 보여주기');
    expect(html).toContain('대리대출을 신청하려면 먼저 신용보증재단 보증서가 필요한지 확인하세요. 보증서 발급에는 1~2주 걸릴 수 있습니다. 보증서가 필요 없으면 직접대출 가능 여부를 바로 비교하세요');
    expect(html).toContain('국세 신고가 끝나도 지방소득세는 위택스에서 따로 신고·납부해야 합니다. 홈택스 연계가 안 되는 세목은 위택스에서 바로 진행하세요');
    expect(html).toContain('재산 처분이 급하면 관리인 선임 청구와 함께 가압류·가처분을 병행하세요. 관리인 선임만으로는 부동산 매각이나 담보 설정을 바로 막을 수 없습니다');
    expect(html).toContain('CASE 49: 탐색 레이블 정리 — 공백 없는 복합어를 풀고 클릭 전 의미를 먼저 보여주기');
    expect(html).toContain('전자증명서안내');
    expect(html).toContain('부가가치세예정신고');
    expect(html).toContain('증명서발급');
    expect(html).toContain('가족관계등록부정정 허가');
    expect(html).toContain('전자증명서 안내');
    expect(html).toContain('부가가치세 예정 신고');
    expect(html).toContain('가족관계 기록 정정 허가');
    expect(html).toContain('탭·카드·검색 결과·추천어는 품사와 길이 통일');
    expect(html).toContain('CASE 10이 입력 필드와 결과 없음 뒤 재검색 단서를 다룬다면, 이 패턴은 검색 결과 카드·추천 레이블까지 클릭 전 의미를 맞추는 규칙입니다.');
    expect(html).toContain('CASE 50: 상담·연락처 안내 — 채널, 대상, 운영시간, 비용을 한 자리에서 보여주기');
    expect(html).toContain('정부민원안내콜센터 국번없이 110 (무료, 휴일포함 365일 24시간)');
    expect(html).toContain('국세상담센터 126상담시간 평일 09시 - 18시');
    expect(html).toContain('손말이음센터(청각장애인용) 107');
    expect(html).toContain('사용자지원센터 일반 통화요금 부과 (별도 정보이용료 없음)');
    expect(html).toContain('정부 민원 안내 110 — 전화·카카오톡·온라인 상담 / 무료 / 365일 24시간');
    expect(html).toContain('국세상담센터 126 — 국세·홈택스 상담 / 일반 통화요금 / 평일 09:00–18:00');
    expect(html).toContain('손말이음센터 107 경유 — 청각·언어장애인 국세상담 / 평일 09:00–18:00 / 126 연결');
    expect(html).toContain('사용자지원센터 — 전자가족관계등록 이용 문의 / 1899-2732, 031-776-7878 / 월~금 09:00–18:00 / 토·일·공휴일 휴무 / 일반 통화요금 / 별도 정보이용료 없음');
    expect(html).toContain('CASE 51: 접근성 레이블 정리 — 번호·이동·새창만 남기지 않고 목적과 상태를 먼저 들려주기');
    expect(html).toContain('서비스 상세 이동');
    expect(html).toContain('1번째 배너');
    expect(html).toContain('AI 켜기');
    expect(html).toContain('가족관계에 관한 영문증명서 발급 서비스 시행 안내 새창');
    expect(html).toContain('창업 초기 지원 서비스 자세히 보기');
    expect(html).toContain('부가가치세 신고 기간 안내 배너 보기');
    expect(html).toContain('AI 검색 사용 중 — 끄려면 클릭');
    expect(html).toContain('가족관계에 관한 영문증명서 발급 서비스 시행 안내 (숨은 정보: 새 탭에서 열림)');
    expect(html).toContain('CASE 52: 중대한 결정 안내 — 효력·기한·되돌릴 수 없는 결과·대안을 먼저 보여주기');
    expect(html).toContain('확정일자 신청');
    expect(html).toContain('현금영수증 발급');
    expect(html).toContain('상속포기 신고');
    expect(html).toContain('지급명령 신청');
    expect(html).toContain('이행권고결정');
    expect(html).toContain('보증금 우선변제 권리 / 현금영수증 의무 발급·가산세 예방 / 상속 채무 승계 차단 / 지급명령 확정 효력 / 이행권고결정 확정 효력');
    expect(html).toContain('전입신고+실거주까지 해야 효력 완성 / 취소·재발급은 1년 이내 / 사망 사실을 안 날부터 3개월·취소 불가 / 지급명령 송달 뒤 2주 이의 / 이행권고결정 수령 뒤 2주 이의');
    expect(html).toContain('등기부등본 확인 / 자진 발급 코드 010-000-1234 / 한정승인과 비교 / 이의신청 시 소송 전환 / 서면·전자소송 이의');
    expect(html).toContain('확정일자 + 전입신고 + 실거주를 모두 해야 보증금 우선변제 권리가 생깁니다. 계약서 원본을 직접 보관하세요');
    expect(html).toContain('의무 발급 대상 여부 확인 + 1년 이내 취소·재발급 + 자진 발급 코드 안내');
    expect(html).toContain('사망 후 3개월 이내 신청 / 취소 불가 / 한정승인과 비교');
    expect(html).toContain('상대방이 2주 이내 이의신청하면 소송으로 전환됩니다. 이의가 없으면 확정 판결과 같은 효력이 생기며, 상대방 주소를 모르면 신청할 수 없습니다. [절차 확인]');
    expect(html).toContain('이행권고결정에 동의하지 않으면 2주 이내 이의신청하세요. 기한을 넘기면 판결과 같은 효력이 생겨 재산이 압류될 수 있습니다. [이의신청 바로 가기]');
    expect(html).toContain('같은 법원의 <code>지급명령 신청</code>은 상대방이 2주 이내 이의신청하면 소송으로 전환되고, <code>이행권고결정</code>은 2주 안에 대응하지 않으면 판결과 같은 효력이 생긴다는 점이 늦게 드러나는 대표 사례입니다.');
    expect(html).toContain('CASE 53: 조회·열람 범위 안내 — 포함·제외 항목과 별도 확인 경로를 먼저 보여주기');
    expect(html).toContain('안심상속 원스톱 서비스 신청');
    expect(html).toContain('금융정보 조회');
    expect(html).toContain('판결문 열람');
    expect(html).toContain('금융계좌·부동산·자동차·세금 채무 / 연간 이자·배당 소득 / 공개 가능한 판결문');
    expect(html).toContain('해외 자산·가상화폐 / 실시간 거래 내역·펀드·보험 / 가사·소년·비공개 결정 사건');
    expect(html).toContain('채무 초과 시 상속포기·한정승인 검토 / 동의 내역 확인·철회 / 제3자 사유서·수수료 확인');
    expect(html).toContain('조회 가능: 금융계좌·부동산·자동차·세금 채무 / 조회 불가: 해외 자산·가상화폐');
    expect(html).toContain('조회 가능: 연간 이자·배당 소득 / 조회 불가: 실시간 거래 내역·펀드·보험 / 동의 관리');
    expect(html).toContain('당사자 온라인 열람 가능 / 제3자 사유서 필요 / 비공개 사건 제외');
    expect(html).toContain('CASE 54: 변경·승인 결과 안내 — 어디에 언제 반영되고 무엇은 별도인지 먼저 보여주기');
    expect(html).toContain('지방세 고지서 수령 방법 선택 (종이·전자)');
    expect(html).toContain('환급금 수령 계좌 등록/변경');
    expect(html).toContain('외국 판결 승인 신청 (이혼)');
    expect(html).toContain('재산세·자동차세·지방소득세 / 최대 5년 치 환급금 / 국내 이혼 효력');
    expect(html).toContain('다음 부과분부터 / 3월 31일까지 신청분은 4월 말까지, 이후 신청분은 신청일부터 3개월 내 / 승인 확정 후');
    expect(html).toContain('알림 미설정 시 미열람 위험 / 환급 신청 전 환급계좌 입력 필요 / 자녀 양육권·재산 분할은 별도 절차');
    expect(html).toContain('변경 적용 세목: 재산세·자동차세·지방소득세 등 / 적용 시점: 다음 부과분부터');
    expect(html).toContain('원클릭으로 최대 5년 치 환급금을 한 번에 신청할 수 있습니다. 3월 31일까지 신청분은 4월 말까지, 이후 신청분은 신청일부터 3개월 내 지급됩니다. 환급계좌를 입력한 뒤 [환급 신청하기]');
    expect(html).toContain('승인 확정 시 국내 이혼 효력 발생 / 자녀 양육권 집행·재산 분할은 별도 절차');
    expect(html).toContain('국세청은 <code>원클릭</code>으로 최대 5년 치 환급금을 한 번에 신청할 수 있고, 3월 31일까지 신청한 환급금은 4월 말까지, 4월 1일 이후 신청분은 신청한 날로부터 3개월 내 지급된다고 안내합니다.');
    expect(html).toContain('CASE 55: 심사·판정 절차 안내 — 누가 무엇을 기준으로 언제 결정하는지 먼저 보여주기');
    expect(html).toContain('장기요양인정 신청');
    expect(html).toContain('종합소득세 신고 도움');
    expect(html).toContain('개명 허가 신청');
    expect(html).toContain('만 65세 이상 또는 노인성 질병 / 업종·수입 금액 기준 / 사회생활 불편·종교·관습 사유');
    expect(html).toContain('방문 조사 7~10일 / 자동 판정 근거 확인 / 법원 심사 1~3개월');
    expect(html).toContain('30일 내 결과 통지 / 입력 즉시 판정 근거 확인 / 기각 시 1주일 이내 즉시항고');
    expect(html).toContain('신청 가능: 만 65세 이상 또는 노인성 질병 / 방문 조사 7~10일 / 판정위원회 심의 30일');
    expect(html).toContain('왜 단순경비율인지: 업종·수입 금액 기준 / 자동 반영 항목과 직접 입력 항목 구분');
    expect(html).toContain('허가 기준 + 통상 1~3개월 / 기각 시 1주일 이내 즉시항고');
    expect(html).toContain('CASE 56: 대기·지연 상태 안내 — 지금 어디까지 왔고 늦어지면 어디로 가야 하는지 먼저 보여주기');
    expect(html).toContain('처리 중');
    expect(html).toContain('환급금: 120,000원');
    expect(html).toContain('담당 기관에서 답변을 준비하고 있습니다.');
    expect(html).toContain('답변 예정일 2026.06.12 / 세금 환급 예상 입금일 2026.06.18 / 국적이탈 신고 심사 최대 6개월');
    expect(html).toContain('답변이 늦어지면 나의 민원에서 다시 확인 / 접수번호로 처리 현황 조회 / 환급이 늦으면 계좌 정보와 지연 사유 확인');
    expect(html).toContain('같은 건이 아니면 새 민원 신청하기 / 답변원문이 등록되면 민원 결과보기 / 보완 요청은 문자·전자문서 확인');
    expect(html).toContain('담당 기관에서 답변을 준비하고 있습니다 / 답변 예정일 2026.06.12 / 나의 민원에서 다시 확인');
    expect(html).toContain('환급 결정 완료 / 예상 입금일 2026.06.18 / 계좌 정보와 지연 사유 확인');
    expect(html).toContain('국적이탈 신고서 접수 / 최대 6개월 / 접수번호로 처리 현황 조회');
    expect(html).toContain('정부24의 <code>온라인 민원 신청 진행 상태</code>는 처리 기한이 지나도 접수번호와 문의 경로가 한 번에 보이지 않고,');
    expect(html).toContain('CASE 57: 복수 조건 체크리스트 안내 — 나이·소득·재산·기한처럼 모두 충족해야 하는 기준을 먼저 보여주기');
    expect(html).toContain('긴급복지지원 신청');
    expect(html).toContain('근로장려금 신청');
    expect(html).toContain('국적 이탈 신고');
    expect(html).toContain('위기 상황 + 소득·재산 기준 / 가구 유형별 소득 + 재산 기준 / 복수 국적 + 병역 + 기한');
    expect(html).toContain('중위소득 75% 이하 + 재산 기준 / 재산 2억 4천만 원 미만 / 만 18세가 되는 해 3월 31일까지');
    expect(html).toContain('조건 미충족 시 대상 아님 / 재산 기준 초과 시 지급 제외 / 기한 초과 시 병역 이행·면제 후 신청');
    expect(html).toContain('[자가 확인] [가구 유형별 기준] [국적 이탈 요건 확인]');
    expect(html).toContain('위기 상황 + 소득·재산 기준 모두 충족 [자가 확인]');
    expect(html).toContain('소득 기준 + 재산 기준 모두 충족 / 반기·정기 신청 방식 확인');
    expect(html).toContain('복수 국적 + 병역 + 기한 모두 충족 [요건 확인]');
    expect(html).toContain('같은 체크리스트 구조는 전자가족관계등록시스템의 <code>협의이혼 의사확인 신청</code>에서도 반복됩니다. 배우자 두 분 방문, 숙려기간 경과, 미성년 자녀 협의서 가운데 하나라도 빠지면 절차가 멈춥니다.');
    expect(html).toContain('홈택스의 <code>공동사업장 등록 신청</code>도 지분 비율, 손익 귀속, 지분 변동 신고 기한을 함께 확인해야 한다는 점에서 같은 문제입니다.');
    expect(html).toContain('CASE 30이 대상 여부와 허가 기준을 먼저 드러내는 일반 규칙이라면, 이 패턴은 조건이 둘 이상일 때 각 항목을 끊어 보여주고 스스로 통과 여부를 확인하게 하는 규칙입니다.');
    expect(html).toContain('CASE 58: 담당 기관·관할 안내 — 어디에서 처리되는지와 예외를 먼저 보여주기');
    expect(html).toContain('이사한 주소 기준 주민센터·구청 / 사업장 주소 변경 시 관할 세무서 자동 변경 / 단순 오기재는 시·구청, 출생일·성명 정정은 법원 허가');
    expect(html).toContain('혼자 이사인지 / 정정 항목이 무엇인지 / 단순 오기재인지 법원 허가 대상인지');
    expect(html).toContain('[담당 기관 찾기] [담당 세무서 확인] [절차 안내] [관할 법원 찾기]');
    expect(html).toContain('이사한 주소 기준 주민센터·구청 신고 [담당 기관 찾기]');
    expect(html).toContain('정정 항목별 온라인 가능 여부 + 관할 세무서 자동 변경 확인');
    expect(html).toContain('단순 오기재인지, 법원 허가가 필요한 정정인지 먼저 확인');
    expect(html).toContain('온라인/방문 분기가 가능한 채널을 가르는 규칙이라면, 이 패턴은 어느 주민센터·세무서·법원 절차에서 내 일을 처리하는지까지 보여주는 규칙입니다.');
    expect(html).toContain('CASE 59: 대리·위임 권한 안내 — 누가 대신할 수 있고 어디까지 맡기는지 먼저 보여주기');
    expect(html).toContain('병적증명서 발급');
    expect(html).toContain('세무대리인 수임 동의');
    expect(html).toContain('소송 대리인 등록');
    expect(html).toContain('본인 또는 위임장 지참 대리인 / 세무사 홍길동님에게 위임 / 변호사 소송 대리인 등록');
    expect(html).toContain('위임장 + 신분증 / 2026.01~2026.12 신고·납부 내역 조회·납부 대리 / 서류 제출·기록 열람·기일 신청·항소');
    expect(html).toContain('대리 발급 전 위임장 확인 / 계좌 변경 제외·수임 해지 / 제한 위임은 위임장 명시·해임 신고 필요');
    expect(html).toContain('[대리 발급 안내] [공개 정보 목록 보기] [해임 방법 보기]');
    expect(html).toContain('본인 또는 위임장 지참 대리인 신청 가능');
    expect(html).toContain('2026.01~2026.12 신고·납부 대리 / 계좌 변경 제외 / [수임 해지]');
    expect(html).toContain('서류 제출·열람·기일 신청·항소 대리 / 제한 위임·해임 신고 안내');
    expect(html).toContain('CASE 19가 본인·가족·이해관계인처럼 신청 주체를 나누는 규칙이라면, 이 패턴은 이미 누군가에게 내 일을 맡기는 순간 권한 범위와 종료 방법을 먼저 보여주는 규칙입니다.');
    expect(html).toContain('CASE 60: 절차 선택 안내 — 어떤 상황에 어떤 절차가 맞는지 먼저 보여주기');
    expect(html).toContain('진정 / 청원 / 제안 / 신고');
    expect(html).toContain('휴업·폐업 신고');
    expect(html).toContain('개인회생 신청서 제출 / 개인 파산 신청');
    expect(html).toContain('기관 처분 이의 / 위법 신고 / 제도 개선 / 공식 의견 제출');
    expect(html).toContain('잠시 쉬기(휴업) / 완전 종료(폐업) + 신고 뒤 해야 할 일');
    expect(html).toContain('소득이 있으면 개인회생 / 상환이 어렵다면 파산 검토');
    expect(html).toContain('기관 처분 이의 / 위법·부정 행위 제보 / 제도 개선 의견 / 잠시 쉬기 vs 완전 종료 / 소득이 있어 분할 상환 vs 상환 어려움');
    expect(html).toContain('진정·청원·제안·신고 차이 / 휴업은 최대 2년, 폐업은 등록 말소 + 사후 신고 / 개인회생은 나눠 갚기, 파산은 상환 불가');
    expect(html).toContain('담당 기관 오배정·반려 / 재고 부가세·사후 신고 누락 / 절차를 다시 판단해야 할 수 있음');
    expect(html).toContain('성년후견 개시 심판 청구');
    expect(html).toContain('CASE 34가 등급·방식별 비용·혜택을 비교하는 규칙이고 CASE 14가 이미 고른 절차 안의 준비물·처리 기간을 설명하는 규칙이라면, 이 패턴은 그보다 앞에서 어떤 절차 자체가 맞는지 가르는 규칙입니다.');
    expect(html).toContain('지금 내 상황, 절차별 선택 기준, 잘못 고를 때 생기는 재판단 비용, 비교·상담·진입 경로');
    expect(html).toContain('법무부 심사 최대 6개월');
    expect(html).toContain('로그인·실명확인 정보는 120분 동안 유지됩니다. 5분 뒤 자동으로 로그아웃됩니다. 작성 중인 내용은 임시 저장됩니다.');
    expect(html).toContain('5분 뒤 자동으로 로그아웃됩니다');
    expect(html).toContain('메인으로 가기');
    expect(html).toContain('인증서가 30일 후 만료됩니다');
    expect(html).toContain('부가가치세 신고 마감까지 30일 남았습니다');
    expect(html).toContain('항소 기한: 5월 9일까지 (7일 남음)');
    expect(html).toContain('신고인이 본인이면 인터넷 신청 가능');
    expect(html).toContain('홈택스에서 정정 신고·증빙 전자제출 가능');
    expect(html).toContain('판결·조정조서 집행은 제1심법원에 신청');
    expect(html).toContain('임대차계약서·집주인 확인서 / 사업자등록증·변경 증빙 / 집행문부여신청서·판결정본·확정증명원·송달증명원');
    expect(html).toContain('필수 서류 보기');
    expect(html).toContain('관계별 서류 확인 — 부모 등록은 가족관계증명서 + 소득 확인서 필요');
    expect(html).toContain('본인 자료는 바로 조회 / 부양가족 자료는 온라인 동의 또는 세무서 방문 필요');
    expect(html).toContain('당사자는 온라인 열람 가능 / 이해관계인은 소명 서류 + 허가 절차 필요 / 제3자는 법원 방문 신청');
    expect(html).toContain('정부24의 <code>부동산 거래 신고</code>도 직거래인지 공인중개사 거래인지에 따라 매도인·매수인이 함께 신고해야 하는지, 중개사가 대신 신고하는지가 갈리는데 시작 전에 한 줄로 정리되지 않습니다.');
    expect(html).toContain('공동 신고가 필요한 화면이라면 <strong>함께 신청해야 하는 사람</strong>도 같은 영역에서 바로 보여줘야 합니다.');
    expect(html).toContain('외국인입니다 — 외국인등록번호 입력 (해당자만 필수)');
    expect(html).toContain('수출 실적이에요 — 수출신고필증 + 외화입금 증빙 첨부');
    expect(html).toContain('미성년 자녀가 있어요 — 친권·양육자 지정 협의서 필수 제출');
    expect(html).toContain('외국인등록번호 추가 입력 / 영세율 증빙 미흡 시 과세 전환 위험 / 미성년 자녀 협의서 없으면 이혼 불성립');
    expect(html).toContain('민원 답변 결과를 입력한 이메일로 보냅니다. 기관 답변이 등록된 뒤 [나의 민원]에서 다시 확인할 수 있습니다.');
    expect(html).toContain('국세고지서·납부통지서·환급금 통지서를 우편 대신 전자로 받습니다. 신청일 다음 날 이후 새로 생성된 서류부터 적용됩니다. [전자송달 신청] [고지서 다시 보기]');
    expect(html).toContain('재판기일지정·문건접수 정보는 알림톡으로 먼저, 불가하면 문자로 받습니다. 문건접수·전자송달·종국내용은 실시간, 기일등록·변경은 12:00와 19:00에 발송됩니다. [알림서비스 신청] [사건 진행내역 확인]');
    expect(html).toContain('답변 등록 완료 후 나의 민원 / 고지서 다시 보기 / 사건 진행내역');
    expect(html).toContain('[나의 민원] [전자송달 신청] [고지서 다시 보기] [알림서비스 신청] [사건 진행내역 확인]');
    expect(html).toContain('`이메일`, `전자고지`, `알림서비스` 같은 채널 이름만으로는 새 사전 항목을 만들지 말고');
    expect(html).toContain('자격·조건 화면: 대상 여부 / 기준값 / 탈락 조건 / 자가 확인 경로');
    expect(html).toContain('긴급·병행 화면: 먼저 연결할 채널 / 같이 해야 할 외부 절차 / 복귀 경로 / 누락·중복 확인 경로');
    expect(html).toContain('가족 전체 주민등록증명서 (등본) — 대출·계약·학교 제출');
    expect(html).toContain('상세 가족관계증명서 — 전 가족 기록 포함, 상속·이민 제출');
    expect(html).toContain('금융거래용 납세증명서 — 은행·대출 제출');
    expect(html).toContain('공개 범위 선택 — 필요한 정보만 보이게 하고 권장 범위를 먼저 보여주기');
    expect(html).toContain('은행·학교 제출 / 법원 제출 / 세무사 위임');
    expect(html).toContain('은행·학교 제출용 — 주민번호 뒷자리는 제외하고 필요한 항목만 선택');
    expect(html).toContain('대출·담보 제출용 — 말소 포함 전체 / 소송 제출용 — 현재 유효만');
    expect(html).toContain('세무사 홍길동님이 2026.01~2026.12 동안 신고·납부 내역을 열람합니다. 마이페이지에서 해제할 수 있습니다');
    expect(html).toContain('첨부 파일 업로드 — 제한 조건과 재제출 경로를 먼저 보여주기');
    expect(html).toContain('민원 증빙 / 전자소송 PDF / 세무 소명 자료');
    expect(html).toContain('PDF·JPG·HWP 가능 · 파일당 최대 5MB · 최대 3개');
    expect(html).toContain('HWP 파일은 제출 불가합니다. PDF로 변환 후 다시 업로드해 주세요');
    expect(html).toContain('허용 형식: PDF·JPG·HWP | 파일당 5MB | 총 20MB | 판독 불가 시 재제출 바로 가기');
    expect(html).toContain('이용 불가 안내 — 복구 시각과 대체 경로를 먼저 보여주기');
    expect(html).toContain('서버 점검 중 / 위택스 연계 중단 / 일시 오류');
    expect(html).toContain('지금은 이 서비스를 이용할 수 없습니다. 서버 점검 중이며 오늘 오후 6시에 다시 열립니다. 급하신 경우 가까운 주민센터를 방문해 주세요');
    expect(html).toContain('위택스 연계가 지금은 중단됐습니다. 납부 처리 상태를 먼저 확인하고, 필요하면 위택스로 직접 이동해 주세요');
    expect(html).toContain('일시적인 오류가 발생했습니다. 10분 뒤 다시 시도해 주세요. 계속되면 1899-2732로 문의하거나 가까운 법원 종합민원실을 방문해 주세요');
    expect(html).toContain('이용 환경 안내 — 어떤 기기에서 가능한지와 전환 경로를 먼저 보여주기');
    expect(html).toContain('모바일 웹 / 정부24 앱 / PC');
    expect(html).toContain('앱에서는 모바일 신분증 발급·알림 수신·간편인증이 가능해요. [앱 열기] [앱 다운로드]');
    expect(html).toContain('이 서비스는 PC에서 이용하실 수 있습니다. [PC로 이동하는 QR코드 보기]');
    expect(html).toContain('일부 서비스(증명서 발급·신고)는 PC에서만 이용하실 수 있습니다. PC에서 다시 접속해 주세요');
    expect(html).toContain('전자 발급본 안내 — 효력과 진위확인 경로를 먼저 보여주기');
    expect(html).toContain('문서확인번호 / QR코드 / 증명서 진위확인');
    expect(html).toContain('전자 발급본도 출력 시 원본과 동일 효력 / 전자 발급본이 공문서와 동일한 효력');
    expect(html).toContain('문서확인번호 1234-5678-9012 / QR로 진위 확인 / 정부24는 발급 후 7일 내 무료 재출력');
    expect(html).toContain('전자 발급본도 출력 시 원본과 동일 효력 / 공공 마이데이터 제출 또는 PDF 첨부');
    expect(html).toContain('전자가족관계등록시스템도 <code>증명서 진위확인</code> 메뉴에서 발급일 기준 3개월 안에 좌측 하단 발급번호로 확인하도록 안내하므로');
    expect(html).toContain('발급일 기준 3개월 이내 발급번호로 진위 확인');
    expect(html).toContain('문서확인번호 또는 발급번호, 전자 발급본 효력, 공공 마이데이터·PDF 제출 경로, 발급일 기준 3개월 이내 진위확인, 처리내역 다시 확인 경로를 함께 적습니다.');
    expect(html).toContain('문서확인번호와 QR코드로 진위 확인하기 / 발급번호 확인하기 / 전자 발급본 제출 경로 확인하기 / 처리내역 다시 확인하기');
    expect(html).toContain('발급 제한·예외 안내 — 조건과 다음 경로를 먼저 보여주기');
    expect(html).toContain('세대 정보 함께 표시 / 다른 국세 체납 여부 확인 / 집행권원에 따라 신청처 분기');
    expect(html).toContain('주민등록표 등본에는 한 세대 구성원 정보가 함께 표시됩니다. 온라인은 본인만 신청할 수 있고, 대리 신청은 방문 시 위임장을 준비합니다. [대리 신청 서류 보기]');
    expect(html).toContain('납세증명서는 발급일 현재 다른 국세 체납 사실이 없을 때 발급됩니다. 지금 발급되지 않으면 [체납 내역 확인]부터 진행하세요.');
    expect(html).toContain('집행문은 서류 종류에 따라 신청처가 다릅니다. 판결·조정조서는 제1심법원에, 소송기록이 상급심에 있으면 그 법원에, 공정증서는 작성 공증인사무소에 신청합니다. [신청처 확인]');
    expect(html).toContain('반려·보완 요청 — 사유와 정정 경로를 먼저 보여주기');
    expect(html).toContain('완료');
    expect(html).toContain('판독 불가');
    expect(html).toContain('신고 불수리 통지 조회');
    expect(html).toContain('보완 요청 — 추가 제출 서류가 있습니다. ○월 ○일까지 [보완 서류 제출]');
    expect(html).toContain('보완 요청 — 스캔본 판독이 어려워 다시 제출해 주세요. ○월 ○일까지 [재제출 바로 가기]');
    expect(html).toContain('신고 반려 통지 확인 — 거부 사유 보기 / [다시 신고하기]');
    expect(html).toContain('신청 가능 조건 안내 — 대상 여부와 허가 기준을 먼저 보여주기');
    expect(html).toContain('세대주 변경 신고');
    expect(html).toContain('사업장 현황 신고');
    expect(html).toContain('개명 허가 신청');
    expect(html).toContain('세대 대표자 변경 신고 (세대주 변경) — 기존 세대주의 동의가 필요합니다');
    expect(html).toContain('부가가치세 면세 사업자는 매년 2월 10일까지 신고해야 합니다. [내 업종 확인]');
    expect(html).toContain('개명 허가 기준 — 사회생활 불편 / 종교·관습 사유 / 기타 정당한 사유');
    expect(html).toContain('후속 처리 안내 — 완료·허가 뒤 다음 기관·문서·기한을 먼저 보여주기');
    expect(html).toContain('전입신고가 완료되었습니다');
    expect(html).toContain('원천세 수정 신고 / 경정 청구');
    expect(html).toContain('개명 허가');
    expect(html).toContain('주소 변경이 완료됐습니다. 자동 반영: 국민연금·건강보험 / 별도 변경: 자동차등록·금융기관 [변경 체크리스트]');
    expect(html).toContain('세금을 더 내야 하면 수정 신고 / 돌려받아야 하면 경정 청구. 감면 기한·청구 기한 [선택 기준 보기]');
    expect(html).toContain('개명 허가 후 1개월 이내 주민센터 신고가 필요합니다. 주민등록증 → 운전면허증 → 여권 → 금융 계좌 순으로 변경하세요 [체크리스트 보기]');
    expect(html).toContain('혜택·의무 안내 — 자동 적용과 별도 신청·신고를 먼저 보여주기');
    expect(html).toContain('장애 정도 결정 통지');
    expect(html).toContain('환급금: 120,000원');
    expect(html).toContain('국적 회복 허가');
    expect(html).toContain('장애 정도가 결정됐습니다. 지금 신청 가능한 혜택: 장애인연금 / 활동 지원 / 교통 요금 할인 등록 [혜택 신청]');
    expect(html).toContain('환급금 120,000원 — 체납 세금이 있으면 먼저 충당되고 잔액만 입금됩니다. 계좌가 없으면 [환급 계좌 등록]');
    expect(html).toContain('한국 국적 다시 받기 허가 결과를 먼저 확인해 주세요. 1년 내 외국 국적 포기 절차를 진행하고, 외국국적불행사서약 대상인지 확인해 주세요. 외국 국적 포기 증명서 제출 경로 확인 [신고 방법 보기]');
    expect(html).toContain('결과 불복·재심사 안내 — 가능 여부·기한·다음 절차를 먼저 보여주기');
    expect(html).toContain('심사청구');
    expect(html).toContain('불복청구');
    expect(html).toContain('지급명령 이의신청');
    expect(html).toContain('결과에 이의가 있다면 통지일로부터 90일 이내 심사 청구할 수 있습니다. [이의신청 방법]');
    expect(html).toContain('세금 부과에 이의가 있으신가요? 고지일로부터 90일 이내 이의신청·심판청구가 가능합니다. [절차 보기]');
    expect(html).toContain('지급명령에 동의하지 않으면 2주 이내 이의신청하세요. 이후 민사소송으로 전환되며 답변서 제출이 필요합니다. [이의신청 바로 가기]');
    expect(html).toContain('비교 선택 안내 — 등급·방식별 차이와 예상 비용·혜택을 먼저 보여주기');
    expect(html).toContain('노인장기요양 등급 신청');
    expect(html).toContain('주택임대소득 분리과세 / 종합과세 선택');
    expect(html).toContain('소액사건심판 신청');
    expect(html).toContain('1~2등급은 시설 입소 가능 / 3~5등급은 방문요양·주야간보호 중심 / 인지지원등급은 인지 프로그램 이용. 본인부담은 재가 15%, 시설 20%입니다 [등급별 서비스 비교]');
    expect(html).toContain('연 임대 수입 2,000만 원 이하라면 분리과세 14%와 종합과세 6~45% 중 선택할 수 있습니다. 다른 소득이 높으면 분리과세가, 낮으면 종합과세가 유리할 수 있습니다 [예상세액 비교]');
    expect(html).toContain('3,000만 원 이하 금전 청구라면 소액사건으로 신청할 수 있습니다. 보통 1~2회 기일로 끝나며 변호사 없이도 진행할 수 있습니다 [일반소송과 비교]');
    expect(html).toContain('예상 계산 안내 — 계산 기준·포함 항목·제외 조건을 먼저 보여주기');
    expect(html).toContain('자동차 이전 등록 신청');
    expect(html).toContain('부동산 임대소득 신고');
    expect(html).toContain('인지대·송달료 계산');
    expect(html).toContain('취득가액 입력 → 취득세 + 채권 매입 예상액 자동 표시. 경차·전기차는 취득세 감면 가능, 채권은 즉시 할인 매도할 수 있습니다 [감면 기준 확인]');
    expect(html).toContain('전세 보증금을 받는다면 간주임대료 계산이 필요합니다. 보증금 × 2.9% × 임대 기간/365. 1주택 비과세 여부와 경비 공제도 같이 확인하세요 [간주임대료 계산기]');
    expect(html).toContain('청구금액 입력 → 인지대 + 송달료 자동 계산. 인지대는 법원 수수료, 송달료는 서류 발송 우편 비용입니다 [소송비용 상세 계산]');
    expect(html).toContain('예상값 안내 — 확정 시점·달라질 수 있는 변수·정산 경로를 먼저 보여주기');
    expect(html).toContain('건강보험료 경감 신청');
    expect(html).toContain('근로장려금 신청');
    expect(html).toContain('부동산 강제경매 신청');
    expect(html).toContain('현재 월 보험료 기준 예상 경감액입니다. 소득·거주지 변동이나 연 1회 정기 재심사 결과에 따라 달라질 수 있습니다 [변동 신고]');
    expect(html).toContain('반기 신청은 예상 지급액의 35%만 먼저 지급되고, 나머지는 다음 해 정산합니다. 배우자 소득·재산이 반영되면 실제 지급액이 달라질 수 있습니다 [정산 기준 확인]');
    expect(html).toContain('예상 배당액은 선순위 담보·임차인 보증금·집행 비용에 따라 달라질 수 있으며 0원일 수도 있습니다. 취하 시 미사용 예납금만 환급됩니다 [배당 순위 확인]');
    expect(html).toContain('결과 연결 CTA — 비교·계산 뒤 다음 신청·신고·집행을 바로 보여주기');
    expect(html).toContain('국민연금 가입 내역');
    expect(html).toContain('부가가치세 예정신고');
    expect(html).toContain('지급명령 신청');
    expect(html).toContain('폼 도움말 — 법령 용어를 첫 레이블 아래로 내리기');
    expect(html).toContain('실명확인 / 자료제공동의 / 간주임대료 / 인지대·송달료 계산 / 임의가입·추납');
    expect(html).toContain('본인 확인 — 실명확인 절차입니다. 확인이 끝나면 다음 단계로 넘어갑니다.');
    expect(html).toContain('국민신문고의 <code>실명확인</code>');
    expect(html).toContain('관찰 사이트</strong> 국민신문고, 정부24, 홈택스, 대한민국법원');
    expect(html).toContain('사업자 유형 — 개인 일반과세자는 예정 고지 대상인지 먼저 확인하세요.');
    expect(html).toContain('전세 보증금 — 전세 보증금이 있으면 간주임대료 계산이 필요합니다.');
    expect(html).toContain('청구금액 — 청구금액을 입력하면 인지대와 송달료를 자동 계산합니다.');
    expect(html).toContain('가입 공백 기간 — 못 낸 기간 보험료는 추납으로 나중에 낼 수 있습니다.');
    expect(html).toContain('이 기간을 추납하면 수령액이 월 ○○만 원 늘어납니다. 지금 바로 [추납 신청]');
    expect(html).toContain('직전 과세 기간 대비 매출이 1/3 이하로 줄었다면 예정 신고를 직접 선택해 납부세액을 줄일 수 있습니다 [신고 선택]');
    expect(html).toContain('지급명령이 확정된 뒤에도 채무자가 갚지 않으면 바로 [강제집행 신청]할 수 있습니다. 예금·급여·부동산 압류 가능');
    expect(html).toContain('통신판매중개자 / 노무제공플랫폼사업자');
    expect(html).toContain('통신판매중개자·노무제공플랫폼사업자 고용보험 안내.');
    expect(html).toContain('소득인정액 아래에 `소득평가액`, `소득환산액` 같은 용어가 이어지면');
    expect(html).toContain('점·슬래시·괄호를 분리 신호로 먼저 봅니다.');
    expect(html).toContain('대리·관할 화면: 처리 기관 또는 관할 / 대리 가능 대상 / 권한 범위 / 해지·예외 경로');
    expect(html).toContain('조회·발급·공개 범위 화면: 포함 항목 / 빠지는 항목 / 효력 또는 유효기간 / 별도 확인 경로');
  });

  it('records the archive-to-case workflow in the public-service corpus log', () => {
    const corpus = fs.readFileSync(path.join(process.cwd(), 'research/public-service-corpus.md'), 'utf8');

    expect(corpus).toContain('| `case-studies/index.html`, `research/public-service-corpus.md`, `tests/case-studies-html.test.js` | 아카이브→CASE 운영 경로 공개 | 사례 운영 가이드 상단에 `이슈 아카이브`를 출발점으로 삼아 `정부24·홈택스·전자가족관계등록시스템 3개 기관 deep archive`를 먼저 대조하고, `원문 3개+CTA 1개`, `기존 CASE 묶음 우선`, `세 대표 사이트 반복 시 사전·원칙·7장·Figma·코퍼스·테스트 동기화`, `용어 1개가 아니라 화면 단계 묶음` 기준으로 승격하는 짧은 절차를 공개한다 |');
    expect(corpus).toContain('| `principles.md`, `principles/safety-net/index.html`, `principles/components/index.html`, `case-studies/index.html`, `research/public-service-corpus.md`, `tests/principles-pages-content.test.js`, `tests/case-studies-html.test.js` | 4장·7장 고용24·응답소 우선 보강 공식 | D-9-3 우선축에 맞춰 고용24 `실업인정 인터넷 신청`은 `실업급여를 확인하는 날 (실업인정일) / 이번 회차 재취업 활동 / 활동을 확인하는 서류 / 실업인정일을 놓치면 이번 회차 지급이 미뤄질 수 있습니다 / 다시 확인 경로`, 서울특별시 응답소 `질의응답·답변원문 / 결과보기`는 `답변 준비 상태 / 답변 예정일 / 나의 민원에서 다시 확인 / 민원 결과보기 / 새 민원 신청하기`를 4장 안전망, CASE 56, 7장 KRDS handoff에 같은 문장으로 추가해 마감일·놓쳤을 때 결과·복구 경로와 CTA 위계를 한 블록으로 맞춘다 |');
    expect(corpus).toContain('| `principles.md`, `principles/safety-net/index.html`, `principles/components/index.html`, `case-studies/index.html`, `research/public-service-corpus.md`, `tests/principles-pages-content.test.js`, `tests/case-studies-html.test.js` | 전자가족관계등록시스템 국적 화면 4장·7장 우선 보강 | 전자가족관계등록시스템 `국적 회복 허가 / 국적 이탈 신고`를 `한국 국적 다시 받기 허가 결과 / 1년 내 외국 국적 포기 / 외국국적불행사서약 대상 여부 / 외국 국적 포기 증명서 제출 경로 / 국적 이탈 가능 기한 / 병역 조건 / 신고 방법 보기 / 요건 확인` 순서로 4장 D-9-3, 7장 D-6-5, CASE 32·45·46·57을 묶는 사례 운영 가이드 승격 메모에 같은 문장으로 추가해 기한·제출 경로·CTA를 한 묶음으로 정렬한다 |');
    expect(corpus).toContain('| `principles.md`, `principles/components/index.html`, `case-studies/index.html`, `research/public-service-corpus.md`, `tests/principles-pages-content.test.js`, `tests/case-studies-html.test.js` | 7장 검색·결과 재확인 공식 재보강 | 국민건강보험 `질병명·병원 이름 검색 / 질환별 건강 정보 / 피부양자 자격취득 / 본인일부부담금 산정특례 제도 / 소득 부과 건강보험료 조정 정산 제도`, 고용24 `훈련 통합검색`, 서울특별시 응답소 `민원 신청하기 / 민원결과 / 결과보기`를 다시 맞춰 `질병명 또는 병원 이름`, `훈련기관명·NCS 직종·능력·자격증·훈련 목표`, `모집 현황·본인부담액`, `민원신청 바로가기 / 민원결과 바로가기`, `민원 결과는 이메일·서신 중 선택한 방법`, `응답소 > 민원결과 > 확인하기`를 7장 KRDS handoff와 CASE 5·10 설명·숨은 레이블·QA까지 같은 문장으로 내린다 |');
  });

  it('keeps thin representative site case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('서울특별시 응답소 질의응답·답변원문, 결과보기');
    expect(html).toContain('답변 준비 상태, 답변 예정일, 나의 민원 재확인, 답변원문 등록 뒤 민원 결과보기, 같은 건이 아니면 새 민원 신청 위계를 함께 적습니다.');
    expect(html).toContain('담당 기관에서 답변을 준비하고 있습니다 / 답변 예정일 2026.06.12 / 나의 민원에서 다시 확인 / 답변원문이 등록되면 민원 결과보기 / 같은 건이 아니면 새 민원 신청하기');
    expect(html).toContain('현재 답변 상태와 예정일 확인하기 / 나의 민원에서 다시 확인하기 / 기존 민원 결과 확인하기 / 같은 건이 아니면 새 민원 신청 시작하기');
    expect(html).toContain('답변 준비 상태, 답변 예정일, 재확인 경로, 민원 결과보기와 새 민원 신청 위계가 첫 결과 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('상태 첫 줄, 답변 예정일, 나의 민원 재확인 경로, 새 민원과 기존 결과 위계를 함께 적습니다.');
    expect(html).toContain('현재 민원 상태와 답변 예정일 보기 / 기존 민원 결과 확인하기 / 새 민원 신청 시작하기');
    expect(html).toContain('민원 결과는 이메일 또는 서신으로도 확인');
    expect(html).toContain('선택한 수신 방법으로 결과 확인하기');
    expect(html).toContain('민원신청 바로가기');
    expect(html).toContain('민원결과 바로가기');
    expect(html).toContain('응답소 &gt; 민원결과 &gt; 확인하기');
    expect(html).toContain('고용24 메인 화면은 <code>실업인정 인터넷 신청</code>, <code>온라인 취업특강 (1차 실업인정 교육)</code>, <code>민원처리현황 (실업급여)</code>를 같은 실업급여 흐름으로 두고');
    expect(html).toContain('<code>실업의 신고일로부터 14일이 지난 후</code>, <code>재취업한 날 또는 사업을 시작한 날부터 12개월이 경과한 이후</code>, <code>조기재취업수당 청구서 및 관련 증빙서류</code>');
    expect(html).toContain('실업급여를 확인하는 날과 취업한 날 기준, 실업 신고 뒤 14일이 지난 뒤 재취업했는지, 12개월이 지난 뒤 청구하는 시점, 조기재취업 대상 여부·확인 서류, 놓쳤을 때 결과와 다시 확인 경로를 함께 적고, 플랫폼 예외는 Disclosure와 Helper text로 분리합니다.');
    expect(html).toContain('실업급여를 확인하는 날과 다시 확인 경로 보기 / 취업한 날 기준 확인하기 / 조기재취업수당 대상과 확인 서류 보기 / 12개월이 지난 뒤 청구 서류 준비하기 / 플랫폼 유형 예외 확인하기');
    expect(html).toContain('같은 고용24 흐름에서 조기재취업 대상이라면 <code>[조기재취업수당 대상과 확인 서류 보기]</code>, 날짜를 놓쳤다면 <code>[실업인정일을 놓쳤을 때 다시 확인하기]</code>가 바로 이어져야 다음 판단이 끊기지 않습니다.');
    expect(html).toContain('실업급여를 확인하는 날, 이번 회차 재취업 활동, 활동을 확인하는 서류, 취업한 날 기준으로 이어지는 조기재취업 대상 여부·확인 서류, 놓쳤을 때 결과와 다시 확인 경로를 함께 적습니다.');
    expect(html).toContain('실업급여를 확인하는 날까지 재취업 활동을 등록해 주세요 / 활동을 확인하는 서류 보기 / 조기재취업수당 대상과 확인 서류 보기 / 놓쳤다면 다음 회차와 보완 경로 확인');
    expect(html).toContain('조기재취업 대상이라면 [조기재취업수당 대상과 확인 서류 보기], 실업인정일이 지났다면 [실업인정일을 놓쳤을 때 다시 확인하기]로 이어집니다.');
    expect(html).toContain('실업인정일까지 필요한 활동 보기 / 활동을 확인하는 서류 보기 / 취업한 날 기준 확인하기 / 조기재취업수당 대상과 확인 서류 보기 / 실업인정일을 놓쳤을 때 다시 확인하기');
    expect(html).toContain('Description에는 실업급여를 확인하는 날, 이번 회차 재취업 활동, 취업한 날 기준, 조기재취업 대상 여부·확인 서류, 놓쳤을 때 결과와 다시 확인 경로를 함께 적습니다.');
    expect(html).toContain('실업급여를 확인하는 날까지 재취업 활동을 등록해 주세요 / 빨리 다시 취업했을 때 받는 수당 대상과 확인 서류 보기 / 놓쳤다면 다음 회차와 보완 경로 확인');
    expect(html).toContain('실업인정일까지 필요한 활동 보기 / 취업한 날 기준 확인하기 / 조기재취업수당 대상과 확인 서류 보기 / 실업인정일을 놓쳤을 때 다시 확인하기');
    expect(html).toContain('서울특별시 응답소는 홈 화면에서 <code>민원신청 바로가기</code>, <code>민원결과 바로가기</code>를 분리하고');
    expect(html).toContain('<code>응답소에서 신문고를 통해 이관된 민원은 응답소 "민원결과"에서 확인 가능합니다</code>, <code>민원결과 페이지의 "확인하기" 버튼</code> 경로를 다시 안내합니다.');
    expect(html).toContain('<code>사용자 계정 보호를 위해 30분이 지나면 자동 로그아웃</code>');
    expect(html).toContain('화면 목적에 따라 주 CTA 1개와 보조 CTA를 나누고, 결과 재확인 화면인지 새 신청 시작 화면인지 Description과 숨은 레이블에 함께 남깁니다.');
    expect(html).toContain('서울특별시 응답소처럼 <code>답변원문</code>이 등록된 결과 재확인 화면에서는 <code>민원 결과보기</code>가 주 행동이고');
    expect(html).toContain('<code>답변원문</code>이 등록되면 <code>민원 결과보기</code> / 같은 건이 아니면 <code>새 민원 신청하기</code> / <code>참여 이력조회</code>');
    expect(html).toContain('기존 민원 결과 확인하기 / 새 민원 신청 시작하기 / 기존 참여 이력 확인하기');
    expect(html).toContain('입력 범위, 검색 버튼 이름, 결과 없음 뒤 재검색 단서, 결과 카드에서 이어질 다음 CTA를 함께 적습니다.');
    expect(html).toContain('고용24처럼 검색 범위와 결과 카드의 모집 현황·본인부담액이 보이면 그 판단 단서도 함께 적습니다.');
    expect(html).toContain('병원 이름이나 질병명으로 다시 검색하기 / 검색어 전체 지우기 / 훈련 일정과 신청 조건 보기 / 훈련 일정과 모집 현황, 본인부담액 확인하기 / 훈련 과정 신청하기 / 보험료 계산 기준 자세히 보기');
    expect(html).toContain('상태 1문장, 예정일, 재확인 CTA가 첫 결과 영역에서 떨어지지 않는지 확인합니다.');
    expect(html).toContain('실업급여를 확인하는 날, 이번 회차 행동, 활동 확인 서류, 조기재취업 연결 CTA, 놓쳤을 때 보완 경로가 같은 첫 배너에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('결과 재확인 CTA와 새 민원 CTA가 같은 강조 단계로 붙지 않는지, 현재 화면 목적이 첫 버튼 이름에서 바로 보이는지 확인합니다.');
    expect(html).toContain('훈련기관명·자격증·훈련 목표로도 다시 찾아볼 수 있습니다');
    expect(html).toContain('입력 전, 검색 범위, 결과 카드, 결과 없음, 다음 행동이 검색 흐름에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('고용24 <code>훈련 통합검색</code>은 검색 범위를 <code>훈련과정</code>, <code>훈련기관명</code>, <code>NCS 직종·능력</code>, <code>자격증</code>, <code>훈련 목표</code>까지 열어 두고');
    expect(html).toContain('<code>모집 현황</code>, <code>본인부담액</code>');
  });

  it('keeps high-stakes case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('이 절차로 생기는 효력, 신청·취소·이의 기한, 되돌릴 수 없는 결과, 비교할 대안 절차를 함께 적습니다.');
    expect(html).toContain('중대한 결정 효력과 기한 확인하기 / 대안 절차 비교하기 / 이의신청 바로 가기');
    expect(html).toContain('판정 기준, 심사 주체와 단계, 예상 소요 기간, 결과 뒤 다음 행동 또는 불복 경로를 함께 적습니다.');
    expect(html).toContain('판정 기준 자세히 보기 / 심사 단계와 예상 기간 보기 / 불복 방법 확인하기');
    expect(html).toContain('답변이 늦어지면 나의 민원에서 다시 확인 / 접수번호로 처리 현황 조회 / 환급이 늦으면 계좌 정보와 지연 사유 확인');
    expect(html).toContain('답변 지연 시 다시 확인 경로, 답변 예정일, 새 민원으로 넘어가는 기준을 함께 적습니다.');
    expect(html).toContain('현재 답변 상태와 예정일 다시 보기 / 새 민원 신청 시작하기');
    expect(html).toContain('효력, 기한, 취소 불가, 대안 비교가 시작 배너와 첫 목록에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('판정 기준, 단계, 결과 시점, 다음 행동이 시작 영역과 단계 표시기 아래에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('현재 단계, 답변 예정일, 다시 확인 경로, 새 민원 전환 기준이 같은 상태 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('서울특별시 응답소 대표 예시는 답변 준비 상태, 답변 예정일, 나의 민원 재확인, 답변원문이 등록되면 민원 결과보기, 같은 건이 아니면 새 민원 신청 순서로 적습니다.');
    expect(html).toContain('답변 준비 상태를 먼저 확인해 주세요 / 답변이 늦어지면 나의 민원에서 다시 확인해 주세요 / 새 민원 신청하기 / 답변원문이 등록되면 민원 결과보기');
    expect(html).toContain('현재 답변 상태와 예정일 다시 보기 / 새 민원 신청 시작하기 / 기존 민원 결과 확인하기');
    expect(html).toContain('특히 답변 준비 상태, 답변 예정일, 나의 민원 재확인, 민원 결과보기와 새 민원 전환 기준이 같은 상태 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('D-9-3 우선 보강 메모');
    expect(html).toContain('실업급여를 확인하는 날 (실업인정일)');
    expect(html).toContain('실업인정일을 놓치면 이번 회차 지급이 미뤄질 수 있습니다');
    expect(html).toContain('답변원문이 등록되면 민원 결과보기');
    expect(html).toContain('나의 민원에서 다시 확인');
  });

  it('keeps time-bound and continuity case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('신청 가능 기간, 기한 경과 뒤 상태, 병역 또는 예외 조건, 다음 신청 주기·요건 확인 CTA를 함께 적습니다.');
    expect(html).toContain('이번 신청 가능 기간을 먼저 확인해 주세요 / 기한을 넘기면 다음 신청 또는 병역·예외 조건을 확인해 주세요 / 요건 확인');
    expect(html).toContain('이번 신청 가능 기간 확인하기 / 기한 경과 뒤 신청 조건 확인하기 / 다음 신청 일정과 요건 보기');
    expect(html).toContain('기한, 마감 뒤 상태, 병역·예외 조건, 다음 신청 CTA가 같은 첫 배너에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('유지 조건, 자동 종료 또는 전환 시점, 허가 뒤 후속 의무, 신고 방법·전환 CTA를 함께 적습니다.');
    expect(html).toContain('계속 유지되려면 조건을 먼저 확인해 주세요 / 자동 종료 또는 전환 시점 보기 / 국적 회복 허가 뒤 신고 방법 보기');
    expect(html).toContain('유지 조건과 자동 종료 시점 확인하기 / 전환 기준과 후속 의무 보기 / 외국 국적 포기 증명서 제출 경로와 요건 확인하기');
    expect(html).toContain('유지 조건, 자동 종료·전환, 후속 의무, 준비 경로가 같은 상태·결과 영역에서 끊기지 않는지 확인합니다.');
  });

  it('keeps result-follow-up case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('완료 또는 허가 뒤 바로 해야 할 행동, 자동 반영과 별도 변경 대상, 챙겨야 할 문서·기관, 놓치면 생기는 기한 또는 위험을 함께 적습니다.');
    expect(html).toContain('완료 뒤 해야 할 일 확인하기 / 자동 반영과 별도 변경 구분 보기 / 변경 순서 체크리스트 보기');
    expect(html).toContain('결정 뒤 자동으로 이어지는 혜택·처리, 별도 신청·신고가 필요한 항목, 놓치기 쉬운 기한·요건, 바로 가기 CTA를 함께 적습니다.');
    expect(html).toContain('자동 적용 항목 확인하기 / 별도 신청·신고 경로 보기 / 놓치기 쉬운 기한과 요건 확인하기');
    expect(html).toContain('대표 예시는 전자가족관계등록시스템처럼 한국 국적 다시 받기 허가 결과, 1년 내 외국 국적 포기, 외국국적불행사서약 대상 여부, 외국 국적 포기 증명서 제출 경로, 신고 방법 보기 CTA 순서로 적습니다.');
    expect(html).toContain('자동으로 이어지는 혜택 먼저 확인 / 별도 신청·신고 항목 보기 / 놓치기 쉬운 기한과 요건 확인 / 한국 국적 다시 받기 허가 결과를 먼저 확인해 주세요 / 1년 내 외국 국적 포기와 외국국적불행사서약 대상 여부를 확인해 주세요 / 외국 국적 포기 증명서 제출 경로 확인 / 신고 방법 보기');
    expect(html).toContain('국적 회복 허가 결과 확인하기 / 외국 국적 포기 기한과 서약 대상 확인하기 / 외국 국적 포기 증명서 제출 경로 확인하기 / 국적 신고 방법 보기');
    expect(html).toContain('특히 한국 국적 다시 받기 허가 결과, 1년 내 외국 국적 포기, 외국국적불행사서약 대상 여부, 외국 국적 포기 증명서 제출 경로, 신고 방법 CTA가 첫 결과 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('이의신청 또는 재심사 가능 여부, 신청 기한, 기한을 넘겼을 때 결과, 다음 절차·준비물을 함께 적습니다.');
    expect(html).toContain('이의 가능 여부와 기한 확인하기 / 다음 절차 자세히 보기 / 이의신청 바로 가기');
    expect(html).toContain('후속 행동, 연계 기관·문서, 기한, 체크리스트 CTA가 완료 메시지 아래 첫 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('자동 적용, 별도 신청·신고, 기한·요건, 다음 CTA가 같은 결과 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('가능 여부, 기한, 기한 경과 위험, 다음 절차 CTA가 같은 결과 배너에서 끊기지 않는지 확인합니다.');
  });

  it('keeps scope-and-reflection case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('조회·열람에 포함되는 항목, 빠지는 항목, 별도 동의·사유서·비교 절차, 이어지는 CTA를 함께 적습니다.');
    expect(html).toContain('조회 범위 자세히 보기 / 제외 항목 확인하기 / 별도 확인 경로 열기');
    expect(html).toContain('변경 또는 승인 결과가 어디에 반영되는지, 언제 지급되거나 효력이 생기는지, 예외 항목, 환급계좌 입력·별도 처리 경로를 함께 적습니다.');
    expect(html).toContain('적용 범위와 지급 시점 보기 / 예외 항목 확인하기 / 환급계좌 입력 또는 별도 처리 경로 열기');
    expect(html).toContain('포함 범위, 제외 항목, 별도 경로, CTA가 같은 시작 목록이나 접기 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('적용 범위, 지급 또는 반영 시점, 예외, 후속 경로가 같은 완료 영역에서 끊기지 않는지 확인합니다.');
  });

  it('keeps support-and-accessibility case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('상담 채널 이름, 무엇을 도와주는지, 전화번호·연결 경로, 운영시간, 무료 또는 통화요금 여부를 함께 적습니다.');
    expect(html).toContain('정부 민원 안내 110 연결하기 / 국세상담센터 운영시간 보기 / 사용자지원센터 전화번호 확인하기');
    expect(html).toContain('무엇을 여는지, 현재 상태 또는 다음 행동, 새 탭·새 창 여부, 보이는 이름과 맞는 목적 설명을 함께 적습니다.');
    expect(html).toContain('서비스 목적과 동작 함께 읽기 / 현재 상태와 다음 행동 들려주기 / 새 탭 열림 여부 알리기');
    expect(html).toContain('채널 이름, 대상, 번호 또는 연결 경로, 운영시간, 비용 정보가 같은 연락처 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('목적, 상태, 새 탭 여부, 보이는 이름과 숨은 레이블의 일치가 같은 접근성 레이블에서 끊기지 않는지 확인합니다.');
  });

  it('keeps navigation-and-eligibility case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('탭·메뉴·결과 카드에 단어 경계, 지금 하는 일, 대상, 공식 용어 병기 여부를 함께 적습니다.');
    expect(html).toContain('전자증명서 안내 메뉴 열기 / 부가가치세 예정 신고 바로 가기 / 가족관계 기록 정정 허가 자세히 보기');
    expect(html).toContain('모두 충족해야 하는 조건 목록, 기준값, 조건을 못 맞추면 생기는 결과나 다음 경로, 자가 확인 CTA를 함께 적습니다.');
    expect(html).toContain('지원 요건 자가 확인하기 / 가구 유형별 기준 보기 / 국적 이탈 요건 확인하기');
    expect(html).toContain('단어 경계, 행동 동사, 대상, 공식 용어 병기가 같은 탐색 레이블과 추천 카드에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('조건 목록, 기준값, 탈락 시 영향, 자가 확인 CTA가 같은 첫 체크리스트에서 끊기지 않는지 확인합니다.');
  });

  it('keeps follow-up-obligation case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('전자가족관계등록시스템 <code>국적 회복 허가</code>');
    expect(html).toContain('Description에는 <code>한국 국적 다시 받기</code> 같은 시민 언어 헤더와 공식 용어 병기, <code>1년 내 외국 국적 포기</code>, <code>외국국적불행사서약 대상 여부</code>, <code>외국 국적 포기 증명서</code> 제출 경로, <code>[요건 확인]</code>·<code>[신고 방법 보기]</code> CTA를 함께 적습니다.');
    expect(html).toContain('한국 국적 다시 받기 허가 결과를 먼저 확인해 주세요 / 1년 내 외국 국적 포기와 외국국적불행사서약 대상 여부를 확인해 주세요 / 외국 국적 포기 증명서 제출 경로 확인 / 신고 방법 보기');
    expect(html).toContain('국적 회복 허가 결과 확인하기 / 외국 국적 포기 기한과 서약 대상 확인하기 / 외국 국적 포기 증명서 제출 경로 확인하기 / 국적 신고 방법 보기');
  });

  it('keeps routing-and-delegation case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('지금 내야 할 기관, 기관이 갈리는 기준, 예외 경로, 담당 기관 확인 CTA를 함께 적습니다.');
    expect(html).toContain('담당 기관 찾기 / 담당 세무서 확인하기 / 관할 법원 찾기');
    expect(html).toContain('대리 가능한 대상, 필요한 위임장·관계 증빙, 맡길 수 있는 범위, 위임 기간·해지·변경 경로를 함께 적습니다.');
    expect(html).toContain('대리 발급 요건 확인하기 / 위임 범위 자세히 보기 / 수임 해지 또는 해임 방법 보기');
    expect(html).toContain('처리 기관, 갈리는 기준, 예외 경로, 확인 CTA가 같은 첫 분기 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('대상, 증빙, 권한 범위, 종료 경로가 같은 권한 영역에서 끊기지 않는지 확인합니다.');
  });

  it('keeps emergency-and-procedure case cards aligned with KRDS/Figma handoff notes', () => {
    const html = fs.readFileSync(path.join(process.cwd(), 'case-studies/index.html'), 'utf8');

    expect(html).toContain('지금 바로 연결할 채널, 먼저 연결해야 하는 이유, 온라인에서 이어지는 다음 절차, 누락·중복 확인 경로를 함께 적습니다.');
    expect(html).toContain('129 상담 바로 연결하기 / 위택스로 이동하기 / 긴급 보호 연락처 보기');
    expect(html).toContain('같이 해야 하는 절차, 처리 기관 또는 연결 사이트, 먼저·함께 해야 하는 이유, 끝난 뒤 돌아올 복귀 CTA를 함께 적습니다.');
    expect(html).toContain('보증서 필요 여부 확인하기 / 위택스로 이동하기 / 보전 처분 안내 보기');
    expect(html).toContain('지금 내 상황, 절차별 선택 기준, 잘못 고를 때 생기는 위험, 비교·상담·진입 CTA를 함께 적습니다.');
    expect(html).toContain('민원 유형 비교하기 / 휴업·폐업 차이 보기 / 개인회생·파산 비교하기');
    expect(html).toContain('즉시 연결 채널, 우선 행동 이유, 온라인 다음 절차, 확인 경로가 같은 시작 배너에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('병행 절차, 처리 기관, 이유, 복귀 경로가 같은 시작 영역에서 끊기지 않는지 확인합니다.');
    expect(html).toContain('내 상황, 선택 기준, 오선택 위험, 비교·상담 CTA가 같은 첫 분기 영역에서 끊기지 않는지 확인합니다.');
  });
});
